### ISSUE TITLE
config.vm.synced_folder Always mounts as vagrant

### ISSUE THREAD

**Issue by carcus88** [Parallels/vagrant-parallels#100]
I have not been able to find any combination of mounting options that will allow me to mount a synced folder as anything but vagrant

I have tried
    :owner => 'www-data', :group => 'www-data'
And 
    owner: 'www-data', group: 'www-data'

But no matter what every time i do a 
    vagrant reload

The mounts are always vagrant. From the code in this provider it looks like it should be obeying the option but never seems to. This is happening with Vagrant 1.4.1
and Parallels 9

Does anyone else have the same issue or know of a work-around?

**Comment by ssbarnea** [comment]
Sorry to highjack this but I have been trying for months to mount shared folder as non-root and failed. I have a thread on https://forum.parallels.com/threads/how-to-mount-psf-shared-home-folder-as-a-non-root-user.338151/ and opened two tickets with Parallels support. They were not able to provide anything useful, only copy/pasted answers not related to the problem.

**Comment by romankulikov** [comment]
@ssbarnea, seems `share` mount option in prl_fs is what you need.

**Comment by ssbarnea** [comment]
@romankulikov Thanks! I was able to solve the problem using this approach:
cat `/etc/mtab` and copy the line from there to `/etc/fstab` and adding `uid=xxx,gid=xxx`. Doing a `mount -a` and I am done.
