### ISSUE TITLE
`mount_options` in `config.vm.synced_folder` error

### ISSUE THREAD

**Issue by troymccabe** [Parallels/vagrant-parallels#103]
Admittedly, mounted volumes & sharing is not a strong suit of mine, but I've tried everything I can think of to get this working & have been unable to. I'd appreciate any assistance you can provide (or tell me if I'm missing something)
### Issue details

When using VirtualBox as the provider, I need to provide mount_options as so: `[...rest of synced_folder config...], mount_options: ["dmode=775","fmode=664"]`

When I attempt this using Parallels as the provider, I get the following:

```
$ vagrant reload --provision
==> default: Attempting graceful shutdown of VM...
...snip...
==> default: Mounting shared folders...
    default: /var/www => {HOST_DIR}
Failed to mount folders in Linux guest. This is usually because
the "vboxsf" file system is not available. Please verify that
the guest additions are properly installed in the guest and
can work properly. The command attempted was:

mount -t prl_fs -o uid=`id -u vagrant`,gid=`getent group vagrant | cut -d: -f3`,dmode=775,fmode=664 var_www /var/www
mount -t prl_fs -o uid=`id -u vagrant`,gid=`id -g vagrant`,dmode=775,fmode=664 var_www /var/www
```

When I remove `mount_options`, it goes through the mounting process fine, but fails on provision (this failure cascades into other provision actions):

```
Error: Failed to set group to '33': Operation not permitted - /var/www
Error: /Stage[main]/Main/File[/var/www]/group: change from vagrant to www-data failed: Failed to set group to '33': Operation not permitted - /var/www
```

I've also tried `chown`ing & `chmod`ing as the first item in the Puppet manifest, but still no go there either.
### Relevant info

OSX version: 10.9.2
Parallels version: 9.0.24217 rev 979618
Vagrant version: 1.5.1
Box url: https://vagrantcloud.com/parallels/ubuntu-12.04/version/1/provider/parallels.box
Synced folder config:

```
  data['vm']['synced_folder'].each do |i, folder|
    if folder['source'] != '' && folder['target'] != '' && folder['id'] != ''
      nfs = (folder['nfs'] == "true") ? "nfs" : nil
      config.vm.synced_folder "#{folder['source']}", "#{folder['target']}", id: "#{folder['id']}", type: nfs, mount_options: ["dmode=775","fmode=664"]
    end
  end
```

Provider config:

```
  config.vm.provider :parallels do |parallels, override|
    override.vm.box = "dev-parallels"
    override.vm.box_url = "https://vagrantcloud.com/parallels/ubuntu-12.04/version/1/provider/parallels.box"

    parallels.name = data['vm']['box']
    parallels.memory = 512
    parallels.cpus = 2
    parallels.check_guest_tools = false
  end
```

**Comment by hadronzoo** [comment]
@legal90 Do the updates in 10.1.2 make `maproot=root:wheel` irrelevant? I updated Parallels to 10.1.2 and updated the vagrant plugin, but `chown` is still not permitted unless I include the `maproot` option.

**Comment by legal90** [comment]
@hadronzoo 

> I updated Parallels to 10.1.2 and updated the vagrant plugin, but chown is still not permitted

I'd like to reproduce it.
1) Please, show all mount options in this case (`mount` output from the guest VM)
2) Do you have SELinux enabled? (for RHEL-based guests only)

**Comment by itsazzad** [comment]
@legal90 
How is it to use?:
---
  config.nfs.map_uid = Process.uid
  config.nfs.map_gid = Process.gid
---
