### ISSUE TITLE
vagrant up doesn't handle --provision flag

### ISSUE THREAD

**Issue by joelclermont** [Parallels/vagrant-parallels#117]
I have two VMs configured in my Vagrantfile: local and test. Local is my parallels vm. `vagrant up --provision local` responds with:

==> local: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> local: to force provisioning. Provisioners marked to run always will still run.

**Comment by idreesandroid** [comment]
i have the same issue 

E:\vagrant>vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'chrislentz/trusty64-lamp' version '3.0.0' is up to date...
==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> default: flag to force provisioning. Provisioners marked to run always will still run.

**Comment by HamidZandi** [comment]
same here

MACs-MacBook-Pro:Homestead adnan$ vagrant up
Bringing machine 'homestead-7' up with 'virtualbox' provider...
==> homestead-7: Checking if box 'laravel/homestead' version '7.2.1' is up to date...
==> homestead-7: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> homestead-7: flag to force provisioning. Provisioners marked to run always will still run.

**Comment by peekinternational** [comment]
you have to reinstall the window or reset the window then install the vagrant again from first step

**Comment by legal90** [comment]
@idreesandroid @HamidZandi Please note that this is a repository of `vagrant-parallels` - the provider of Parallels Desktop for Mac.

If you are experiencing issues with the built-in `virtualbox` provider, please refer to issues in the Vagrant repo: https://github.com/hashicorp/vagrant/issues
