### ISSUE TITLE
Vagrant-mounted event fires before syncing is complete

### ISSUE THREAD

**Issue by majksner** [Parallels/vagrant-parallels#126]
It seems `vagrant-mounted` doesn't work for some reason. It triggers event but it looks like files are not in sync when the trigger happens.

Upstart:

``` bash
# pm2
description "pm2 start after file sync"
author "Nikola Majksner"

# Listen and start after the vagrant-mounted event
# Even adding MOUNTPOINT=/srv below didn't work
start on vagrant-mounted

script
     sudo -u vagrant -H pm2 resurrect
end script
```

Upstart log file:

```
Process /srv/notification/app.js not launched - (script missing)
```

All above works with virtualbox sync.

**Comment by nickcarenza** [comment]
I think `vagrant-mounted` is emitted for each mount differentiated by the MOUNTPOINT variable. I think you can specify which mount you are interested in `start on vagrant-mounted MOUNTPOINT=/srv` assuming /srv is your mountpoint. You can run `df -T` to see a list of mounts.
