### ISSUE TITLE
Guest Tools never detected as Installed

### ISSUE THREAD

**Issue by bhallturbine** [Parallels/vagrant-parallels#127]
I'm using version 1.1.0 of the vagrant-parallels plugin, vagrant 1.6.3, and Parallels 9.  I've created a box file using packer with Ubuntu 12.04.3 Server and installed parallels tools during provisioning in the box file.

I've also put into the vagrant file to automatically install parallels tools.  

No matter how many times the system does it, it claims parallels tools is not installed (even though it is) and tries again. When I vagrant up --debug, I can see in the log spew that the GuestTools status is "possibly_installed".

VagrantFile Snippets:

```
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = $chef_env

  config.vm.provider :parallels do |pl|  
    pl.update_guest_tools = true
    pl.memory = $vm_memory
    pl.cpus = $vm_cpus
    pl.optimize_power_consumption = false
  end

  config.vm.network "private_network", ip: "192.168.57.3"

  config.vm.synced_folder $services_path, "/usr/local/src/services", create: true
  config.vm.synced_folder $dashboard_path, "/usr/local/src/dashboard", create: true
  config.vm.synced_folder $chat_path, "/usr/local/src/chat", create: true
end
```

Output snippet from vagrant up --debug:

```
        "GuestTools": {
            "state": "possibly_installed",
            "version": "9.0.24237"
        },
```

sometime later

```
==> default: Parallels Tools were not detected on this VM! They are required
==> default: for forwarded ports, shared folders, host only networking and more.
==> default: If SSH fails or shared folders are not working on this machine,
==> default: please install Parallels Tools within the virtual machine and
==> default: reload your VM.
```

**Comment by andremacola** [comment]
I have always this problem here. Give up to use Parallels

**Comment by mikeohara-bsc** [comment]
I am experiencing this, unfortunatly the only way I've been able to recover from this is to destroy the VM and reload it. The VM will run fine for days, even weeks, then all of a sudden I'll shutdown the VM, (vagrant halt) and then start it back up again (vagrant up) and it will throw the tell tale message 
````
==> vmname: Parallels Tools were not detected on this VM! They are required
==> vmname: for forwarded ports, shared folders, host only networking and more.
==> vmname: If SSH fails or shared folders are not working on this machine,
==> vmname: please install Parallels Tools within the virtual machine and
==> vmname: reload your VM.
````

Even after the vm is fully booted, manually sshing into the vm, and running the failed commands, they error out. 

````
root@local:/home/vagrant# mount -t prl_fs -o uid=`id -u vagrant`,gid=`getent group vagrant | cut -d: -f3` vagrant /vagrant
mount: unknown filesystem type 'prl_fs'
root@local:/home/vagrant# mount -t prl_fs -o uid=`id -u vagrant`,gid=`id -g vagrant` vagrant /vagrant
mount: unknown filesystem type 'prl_fs'
````

**Comment by legal90** [comment]
@mikeohara-bsc It might probably caused by Linux kernel upgrade or some changes of kernel modules.
Reinstalling of Parallels Tools should help it this sutuation. Add this to your Vagrantfile and run `vagrant reload` (no need to destroy it):

```ruby
  config.vm.provider :parallels do |p|  
    p.update_guest_tools = true
  end
```
