### ISSUE TITLE
Parallels 10 & 1.2.2, Failed to mount folders

### ISSUE THREAD

**Issue by pulkitjalan** [Parallels/vagrant-parallels#135]
I have just upgraded to parallels 10 and the plugin to 1.2.2. The VMs don't start anymore. It did install Parallels Tools and reboot the vm before getting this error:

```
Failed to mount folders in Linux guest. This is usually because
the "prl_fs" file system is not available. Please verify that
Parallels Tools are properly installed in the guest and
can work properly. If so, the VM reboot can solve a problem.
The command attempted was:

mount -t prl_fs -o uid=`id -u vagrant`,gid=`getent group vagrant | cut -d: -f3`,dmode=775,fmode=755 var_www_html /var/www/html
mount -t prl_fs -o uid=`id -u vagrant`,gid=`id -g vagrant`,dmode=775,fmode=755 var_www_html /var/www/html
```

I also tried 1.2.0 with parallels 9 & 10, and im getting the same error with a slightly different message ("vboxsf" instead of "prl_fs").

I have got it working for now, running version 1.1.0 of the plugin with parallels 9 & 10.

Any idea what might be causing this issue?

(Using ubuntu 14.04 (https://vagrantcloud.com/parallels/ubuntu-14.04))

**Comment by mysterlune** [comment]
Thanks @legal90. Your example override works great.

For those coming along in the wake (like myself), note that "config" is misspelled as "convig" in the current example. No biggie, just make sure to change to the correct spelling or there'll be a big ugly stack output waiting for you when you run your Vagrantfile ;)

**Comment by legal90** [comment]
Oops, Sorry for that mistake :frowning: 
Fixed.

**Comment by mysterlune** [comment]
no problem. thanks!

**Comment by hablutzel1** [comment]
I got around this by manually reinstalling the Parallels Tools for Linux as indicated in https://download.parallels.com/desktop/v12/docs/en_US/Parallels%20Desktop%20User%27s%20Guide/32791.htm
