### ISSUE TITLE
regenerate-src-uuid support does not work when launching multiple machines in parallel

### ISSUE THREAD

**Issue by bassam** [Parallels/vagrant-parallels#153]
Using a multe-machine vagrant file running on OS X Yosemite and using Parallels Desktop 10 (and SDK 10 installed), the UUID of the all machines is the same after running:

```
vagrant up
```

However if I run the following:

```
vagrant up --no-parallel
```

each machine get a unique UUID.

I suspect what is happening is that when launching the machines in parallel the config.pvs file is being overwritten by the last machine launched, but all the machines use the same config.pvs and hence the same UUID.

I wonder if the config.pvs needs to be copied for each machine to support this.

**Comment by bassamtabbara** [comment]
this issue seems to have regressed in Vagrant 1.8.1 using parallels provider 1.6.0. I see the same Source VmUuid generated.

Here's a sample Vagrantfile
```
Vagrant.configure(2) do |config|
  config.vm.box = "AntonioMeireles/coreos-alpha"

  (0..2).each do |i|
    config.vm.define vm_name= "coreos-alpha%d" % i, primary: (i==0) do |node|
      node.vm.hostname = vm_name
      node.vm.provider :parallels do |v|
        v.regen_box_uuid = true
      end
    end
  end
end
```

after a vagrant up:

```
find . /Users/bassam/Documents/Parallels/core* -name config.pvs -exec grep -i SourceVmUuid  {} \;
      <SourceVmUuid>{fa3caf18-f12a-4f73-afd9-786c0640fd59}</SourceVmUuid>
      <SourceVmUuid>{fa3caf18-f12a-4f73-afd9-786c0640fd59}</SourceVmUuid>
      <SourceVmUuid>{fa3caf18-f12a-4f73-afd9-786c0640fd59}</SourceVmUuid>
```

after a vagrant up --no-parallels

```
find . /Users/bassam/Documents/Parallels/core* -name config.pvs -exec grep -i SourceVmUuid  {} \;
      <SourceVmUuid>{5e5caaef-10a6-456d-8716-1359bc6d725c}</SourceVmUuid>
      <SourceVmUuid>{68433599-9b72-4fde-ad81-0f6fcd6de0f9}</SourceVmUuid>
      <SourceVmUuid>{1e59e0cc-e33b-4cb7-b35c-3e6e33721a8a}</SourceVmUuid>
```
