### ISSUE TITLE
Question: Use custom dock icon

### ISSUE THREAD

**Issue by rickard-von-essen** [Parallels/vagrant-parallels#172]
I have been fiddling around a couple of days with the dock icon for VMs (stored in ```<vm>.pvm/<vm>.app/Content/Resources/WinAppHelper.icns```).

After the VM is started it is possible to overwrite this icon and after a restart it show up in the dock. But I can't figure out if:

1) It is possible to set the icon before the VM starts the first time.
2) If it would be possible to supply the icon in a _.box_ file.
3) Is it possible to replace the icon in the _Parallels Desktop Control Center_ shown when the machine is shut down. There is a ```AppBigIcon.png``` but changing this don't seems to change anything.

This might be regarded as slightly fishy stuff, but if it would be possible could lead some nice features.

![screen shot 2015-02-07 at 12 51 08](https://cloud.githubusercontent.com/assets/557699/6092039/50d3bd50-aeca-11e4-8695-b958e1b00c3c.png)

**Comment by legal90** [comment]
@rickard-von-essen 
Currently this mechanism is implemented by a hard way in Parallels Desktop, so it is not meant to be changed by user. 

> 1) It is possible to set the icon before the VM starts the first time.
Unfortunately, it isn't possible. The application stub "<vm>.app" is generated automatically and the content is pre-configured. 

> 2) If it would be possible to supply the icon in a .box file.
Theoretically, we can keep the *.app folder inside the box and we even can put our custom icons there. But this folder will be automatically re-created from scratch after the VM will be renamed.

> 3) Is it possible to replace the icon in the Parallels Desktop Control Center shown when the machine is shut down. There is a AppBigIcon.png but changing this don't seems to change anything.
Seems like icons from Parallels Desktop CC are getting from some other place. I agree that it will be useful to have an opportunity to change it too.

Thank you for a suggestion! :+1: 
It really looks like a good feature for all users of vagrant-parallels and boot2docker as well. We'll try to push an idea to make these icons configurable in Parallels Desktop.

**Comment by rickard-von-essen** [comment]
Nice that you like the idea! Hope support for it can make it into a future version of Parallels Desktop. Thanks for your time!
