### ISSUE TITLE
Folders not mounting anymore

### ISSUE THREAD

**Issue by smichaelsen** [Parallels/vagrant-parallels#174]
I'm using Vagrant with Parallels and I destroyed and rebuilt my previously working machine today, but I get an error that folders could not be mounted:

    $ vagrant up
    Bringing machine 'default' up with 'parallels' provider...
    ==> default: Box 'puphpet/debian75-x64' could not be found. Attempting to find and install...
        default: Box Provider: parallels
        default: Box Version: >= 0
    ==> default: Loading metadata for box 'puphpet/debian75-x64'
        default: URL: https://atlas.hashicorp.com/puphpet/debian75-x64
    ==> default: Adding box 'puphpet/debian75-x64' (v2.0) for provider: parallels
        default: Downloading: https://atlas.hashicorp.com/puphpet/boxes/debian75-x64/versions/2.0/providers/parallels.box
    ==> default: Successfully added box 'puphpet/debian75-x64' (v2.0) for 'parallels'!
    ==> default: Importing base box 'puphpet/debian75-x64'...
    ==> default: Checking if box 'puphpet/debian75-x64' is up to date...
    ==> default: Setting the name of the VM: moony_default_1424343660989_92080
    ==> default: Preparing network interfaces based on configuration...
        default: Adapter 0: shared
        default: Adapter 1: hostonly
    ==> default: Clearing any previously set network interfaces...
    ==> default: Forwarding ports...
        default: 22 => 6260
    ==> default: Setting power consumption mode: "Longer battery life"
    ==> default: Running 'pre-boot' VM customizations...
    ==> default: Booting VM...
    ==> default: Waiting for machine to boot. This may take a few minutes...
        default: SSH address: 10.211.55.10:22
        default: SSH username: vagrant
        default: SSH auth method: private key
        default:
        default: Vagrant insecure key detected. Vagrant will automatically replace
        default: this with a newly generated keypair for better security.
        default:
        default: Inserting generated public key within guest...
        default: Removing insecure key from the guest if its present...
        default: Key inserted! Disconnecting and reconnecting using new SSH key...
    ==> default: Machine booted and ready!
    ==> default: Checking for Parallels Tools installed on the VM...
    ==> default: Parallels Tools were not detected on this VM! They are required
    ==> default: for forwarded ports, shared folders, host only networking and more.
    ==> default: If SSH fails or shared folders are not working on this machine,
    ==> default: please install Parallels Tools within the virtual machine and
    ==> default: reload your VM.
    ==> default: Configuring and enabling network interfaces...
    ==> default: Exporting NFS shared folders...
    ==> default: Preparing to edit /etc/exports. Administrator privileges will be required...
    Password:
    ==> default: Mounting NFS shared folders...
    ==> default: Mounting shared folders...
        default: /vagrant => /Users/smichaelsen/vms/moony
    Failed to mount folders in Linux guest. This is usually because
    the "prl_fs" file system is not available. Please verify that
    Parallels Tools are properly installed in the guest and
    can work properly. If so, the VM reboot can solve a problem.
    The command attempted was:
    
    mount -t prl_fs -o uid=`id -u vagrant`,gid=`getent group vagrant | cut -d: -f3` vagrant /vagrant
    mount -t prl_fs -o uid=`id -u vagrant`,gid=`id -g vagrant` vagrant /vagrant

I'm using a Vagrantfile which I got from puphpet:

require 'yaml'
    
    dir = File.dirname(File.expand_path(__FILE__))
    
    configValues = YAML.load_file("#{dir}/puphpet/config.yaml")
    data         = configValues['vagrantfile-local']
    
    Vagrant.require_version '>= 1.6.0'
    
    Vagrant.configure('2') do |config|
      config.vm.box     = "#{data['vm']['box']}"
      config.vm.box_url = "#{data['vm']['box_url']}"
    
      if data['vm']['hostname'].to_s.strip.length != 0
        config.vm.hostname = "#{data['vm']['hostname']}"
      end
    
      if data['vm']['network']['private_network'].to_s != ''
        config.vm.network 'private_network', ip: "#{data['vm']['network']['private_network']}"
      end
    
      data['vm']['network']['forwarded_port'].each do |i, port|
        if port['guest'] != '' && port['host'] != ''
          config.vm.network :forwarded_port, guest: port['guest'].to_i, host: port['host'].to_i, auto_correct: true
        end
      end
    
      if !data['vm']['post_up_message'].nil?
        config.vm.post_up_message = "#{data['vm']['post_up_message']}"
      end
    
      if Vagrant.has_plugin?('vagrant-hostmanager')
        hosts = Array.new()
    
        if !configValues['apache']['install'].nil? &&
            configValues['apache']['install'].to_i == 1 &&
            configValues['apache']['vhosts'].is_a?(Hash)
          configValues['apache']['vhosts'].each do |i, vhost|
            hosts.push(vhost['servername'])
    
            if vhost['serveraliases'].is_a?(Array)
              vhost['serveraliases'].each do |vhost_alias|
                hosts.push(vhost_alias)
              end
            end
          end
        elsif !configValues['nginx']['install'].nil? &&
               configValues['nginx']['install'].to_i == 1 &&
               configValues['nginx']['vhosts'].is_a?(Hash)
          configValues['nginx']['vhosts'].each do |i, vhost|
            hosts.push(vhost['server_name'])
    
            if vhost['server_aliases'].is_a?(Array)
              vhost['server_aliases'].each do |x, vhost_alias|
                hosts.push(vhost_alias)
              end
            end
          end
        end
    
        if hosts.any?
          if config.vm.hostname.to_s.strip.length == 0
            config.vm.hostname = 'puphpet-dev-machine'
          end
    
          config.hostmanager.enabled           = true
          config.hostmanager.manage_host       = true
          config.hostmanager.ignore_private_ip = false
          config.hostmanager.include_offline   = false
          config.hostmanager.aliases           = hosts
        end
      end
    
      if Vagrant.has_plugin?('vagrant-cachier')
        config.cache.scope = :box
      end
    
      data['vm']['synced_folder'].each do |i, folder|
        if folder['source'] != '' && folder['target'] != ''
          sync_owner = !folder['sync_owner'].nil? ? folder['sync_owner'] : 'www-data'
          sync_group = !folder['sync_group'].nil? ? folder['sync_group'] : 'www-data'
    
          if folder['sync_type'] == 'nfs'
            if Vagrant.has_plugin?('vagrant-bindfs')
              config.vm.synced_folder "#{folder['source']}", "/mnt/vagrant-#{i}", id: "#{i}", type: 'nfs'
              config.bindfs.bind_folder "/mnt/vagrant-#{i}", "#{folder['target']}", user: sync_owner, group: sync_group
            else
              config.vm.synced_folder "#{folder['source']}", "#{folder['target']}", id: "#{i}", type: 'nfs'
            end
          elsif folder['sync_type'] == 'smb'
            config.vm.synced_folder "#{folder['source']}", "#{folder['target']}", id: "#{i}", type: 'smb'
          elsif folder['sync_type'] == 'rsync'
            rsync_args = !folder['rsync']['args'].nil? ? folder['rsync']['args'] : ['--verbose', '--archive', '-z']
            rsync_auto = !folder['rsync']['auto'].nil? ? folder['rsync']['auto'] : true
            rsync_exclude = !folder['rsync']['exclude'].nil? ? folder['rsync']['exclude'] : ['.vagrant/']
    
            config.vm.synced_folder "#{folder['source']}", "#{folder['target']}", id: "#{i}",
              rsync__args: rsync_args, rsync__exclude: rsync_exclude, rsync__auto: rsync_auto, type: 'rsync', group: sync_group, owner: sync_owner
          elsif data['vm']['chosen_provider'] == 'parallels'
            config.vm.synced_folder "#{folder['source']}", "#{folder['target']}", id: "#{i}",
              group: sync_group, owner: sync_owner, mount_options: ['share']
          else
            config.vm.synced_folder "#{folder['source']}", "#{folder['target']}", id: "#{i}",
              group: sync_group, owner: sync_owner, mount_options: ['dmode=775', 'fmode=764']
          end
        end
      end
    
      config.vm.usable_port_range = (data['vm']['usable_port_range']['start'].to_i..data['vm']['usable_port_range']['stop'].to_i)
    
      unless ENV.fetch('VAGRANT_DEFAULT_PROVIDER', '').strip.empty?
        data['vm']['chosen_provider'] = ENV['VAGRANT_DEFAULT_PROVIDER'];
      end
    
      if data['vm']['chosen_provider'].empty? || data['vm']['chosen_provider'] == 'virtualbox'
        ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'
    
        config.vm.provider :virtualbox do |virtualbox|
          data['vm']['provider']['virtualbox']['modifyvm'].each do |key, value|
            if key == 'memory'
              next
            end
            if key == 'cpus'
              next
            end
    
            if key == 'natdnshostresolver1'
              value = value ? 'on' : 'off'
            end
    
            virtualbox.customize ['modifyvm', :id, "--#{key}", "#{value}"]
          end
    
          virtualbox.customize ['modifyvm', :id, '--memory', "#{data['vm']['memory']}"]
          virtualbox.customize ['modifyvm', :id, '--cpus', "#{data['vm']['cpus']}"]
    
          if data['vm']['provider']['virtualbox']['modifyvm']['name'].nil? ||
            data['vm']['provider']['virtualbox']['modifyvm']['name'].empty?
            if data['vm']['hostname'].to_s.strip.length != 0
              virtualbox.customize ['modifyvm', :id, '--name', config.vm.hostname]
            end
          end
        end
      end
    
      if data['vm']['chosen_provider'] == 'vmware_fusion' || data['vm']['chosen_provider'] == 'vmware_workstation'
        ENV['VAGRANT_DEFAULT_PROVIDER'] = (data['vm']['chosen_provider'] == 'vmware_fusion') ? 'vmware_fusion' : 'vmware_workstation'
    
        config.vm.provider :vmware_fusion do |v, override|
          data['vm']['provider']['vmware'].each do |key, value|
            if key == 'memsize'
              next
            end
            if key == 'cpus'
              next
            end
    
            v.vmx["#{key}"] = "#{value}"
          end
    
          v.vmx['memsize']  = "#{data['vm']['memory']}"
          v.vmx['numvcpus'] = "#{data['vm']['cpus']}"
    
          if data['vm']['provider']['vmware']['displayName'].nil? ||
            data['vm']['provider']['vmware']['displayName'].empty?
            if data['vm']['hostname'].to_s.strip.length != 0
              v.vmx['displayName'] = config.vm.hostname
            end
          end
        end
      end
    
      if data['vm']['chosen_provider'] == 'parallels'
        ENV['VAGRANT_DEFAULT_PROVIDER'] = 'parallels'
    
        config.vm.provider 'parallels' do |v|
          data['vm']['provider']['parallels'].each do |key, value|
            if key == 'memsize'
              next
            end
            if key == 'cpus'
              next
            end
    
            v.customize ['set', :id, "--#{key}", "#{value}"]
          end
    
          v.memory = "#{data['vm']['memory']}"
          v.cpus   = "#{data['vm']['cpus']}"
    
          if data['vm']['provider']['parallels']['name'].nil? ||
            data['vm']['provider']['parallels']['name'].empty?
            if data['vm']['hostname'].to_s.strip.length != 0
              v.name = config.vm.hostname
            end
          end
        end
      end
    
      ssh_username = !data['ssh']['username'].nil? ? data['ssh']['username'] : 'vagrant'
    
      config.vm.provision 'shell' do |s|
        s.path = 'puphpet/shell/initial-setup.sh'
        s.args = '/vagrant/puphpet'
      end
      config.vm.provision 'shell' do |kg|
        kg.path = 'puphpet/shell/ssh-keygen.sh'
        kg.args = "#{ssh_username}"
      end
      config.vm.provision :shell, :path => 'puphpet/shell/install-ruby.sh'
      config.vm.provision :shell, :path => 'puphpet/shell/install-puppet.sh'
    
      config.vm.provision :puppet do |puppet|
        puppet.facter = {
          'ssh_username'     => "#{ssh_username}",
          'provisioner_type' => ENV['VAGRANT_DEFAULT_PROVIDER'],
          'vm_target_key'    => 'vagrantfile-local',
        }
        puppet.manifests_path = "#{data['vm']['provision']['puppet']['manifests_path']}"
        puppet.manifest_file  = "#{data['vm']['provision']['puppet']['manifest_file']}"
        puppet.module_path    = "#{data['vm']['provision']['puppet']['module_path']}"
    
        if !data['vm']['provision']['puppet']['options'].empty?
          puppet.options = data['vm']['provision']['puppet']['options']
        end
      end
    
      config.vm.provision :shell do |s|
        s.path = 'puphpet/shell/execute-files.sh'
        s.args = ['exec-once', 'exec-always']
      end
      config.vm.provision :shell, run: 'always' do |s|
        s.path = 'puphpet/shell/execute-files.sh'
        s.args = ['startup-once', 'startup-always']
      end
      config.vm.provision :shell, :path => 'puphpet/shell/important-notices.sh'
    
      customKey  = "#{dir}/files/dot/ssh/id_rsa"
      vagrantKey = "#{dir}/.vagrant/machines/default/#{ENV['VAGRANT_DEFAULT_PROVIDER']}/private_key"
    
      if File.file?(customKey)
        config.ssh.private_key_path = [
          customKey,
          "#{ENV['HOME']}/.vagrant.d/insecure_private_key"
        ]
    
        if File.file?(vagrantKey) and ! FileUtils.compare_file(customKey, vagrantKey)
          File.delete(vagrantKey)
        end
    
        if ! File.directory?(File.dirname(vagrantKey))
          FileUtils.mkdir_p(File.dirname(vagrantKey))
        end
    
        if ! File.file?(vagrantKey)
          FileUtils.cp(customKey, vagrantKey)
        end
      end
    
      if !data['ssh']['host'].nil?
        config.ssh.host = "#{data['ssh']['host']}"
      end
      if !data['ssh']['port'].nil?
        config.ssh.port = "#{data['ssh']['port']}"
      end
      if !data['ssh']['username'].nil?
        config.ssh.username = "#{data['ssh']['username']}"
      end
      if !data['ssh']['guest_port'].nil?
        config.ssh.guest_port = data['ssh']['guest_port']
      end
      if !data['ssh']['shell'].nil?
        config.ssh.shell = "#{data['ssh']['shell']}"
      end
      if !data['ssh']['keep_alive'].nil?
        config.ssh.keep_alive = data['ssh']['keep_alive']
      end
      if !data['ssh']['forward_agent'].nil?
        config.ssh.forward_agent = data['ssh']['forward_agent']
      end
      if !data['ssh']['forward_x11'].nil?
        config.ssh.forward_x11 = data['ssh']['forward_x11']
      end
      if !data['vagrant']['host'].nil?
        config.vagrant.host = data['vagrant']['host'].gsub(':', '').intern
      end
    end
    

Any help is appreciated.

**Comment by legal90** [comment]
The answer is described in the output:

>==> default: Parallels Tools were not detected on this VM! They are required
==> default: for forwarded ports, shared folders, host only networking and more.

Seems like there are no 'Parallels Tools' installed in the box `puphpet/debian75-x64` which is maintained by PuPHPet. So, I've sent a pull-request with hotfix there: https://github.com/puphpet/packer-templates/pull/3

**Comment by legal90** [comment]
@smichaelsen As a temporary solution for you - try to use this box instead: [boscutter/debian75](https://atlas.hashicorp.com/boxcutter/boxes/debian75)

**Comment by smichaelsen** [comment]
Thank you very much for your quick help and also taking care to create a PR!

**Comment by legal90** [comment]
@smichaelsen PuPHPet boxes have been rebuild. Please, check this out:
https://github.com/puphpet/packer-templates/pull/3#issuecomment-75822822
