### ISSUE TITLE
Vagrant randomly loses machine id

### ISSUE THREAD

**Issue by justicel** [Parallels/vagrant-parallels#176]
Howdy. We have a developer (the only person who is having this issue), who uses a lot of rspec test runs which go through vagrant ssh. It appears that randomly vagrant-parallels will lose all of the linked box information like the id, private_key, synced_folders, etc.

It only happens when he runs 'vagrant ssh' and it only happens once in a while so it has been difficult to establish exactly when it occurs or if there's anything special about when this breaks. This results in vagrant thinking the box is down because all of the information is missing. To fix it for now I've been having him get the uuid from 'prlctl list' and adding it back to the id file and then doing a 'vagrant halt; vagrant up'. Still, it's not a very good situation when this happens. Any thoughts?

Thanks!

**Comment by legal90** [comment]
@justicel As I've understood, this issue happens after a successful `vagrant up` and in this case the data directory `.vagrant/machines/<machine_name>/parallels/` becomes empty, without any files and folders inside. Am I rigth?

And could you tell please, how often does it happen?

**Comment by justicel** [comment]
@legal90 It's only when using 'vagrant ssh' commands as far as I can see. I haven't seen an instance where a 'vagrant up' will do it yet.

This happens pretty rarely but I have never seen this occur with standard vagrant+virtualbox in the many years I've used that. If I had to guess, it occurs maybe once every 2-3 weeks.

**Comment by legal90** [comment]
Sorry, I'm gonna close it because there is too small information to figure out what really happens. 

It could be reopened as soon as we get more info
