### ISSUE TITLE
Unsupported mount options?

### ISSUE THREAD

**Issue by rk** [Parallels/vagrant-parallels#177]
I'm getting the `linux_prl_fs_invalid_options` error message when using the following synced_folder option:

	config.vm.synced_folder "html/", "/srv/project/html", owner: 'apache', group: 'apache', mount_options: ['dmode=777' ,'fmode=777']

This has worked with every other provider so far. What's so incorrect about making the folders/files 0777?

**Comment by legal90** [comment]
Duplicates #135
`mount options` are file system specific. `prl_fs` does not support "dmode" and "fmode", which are specific to `vboxsf` from VirtualBox.

So, in your example it should look like this:
```
config.vm.synced_folder "html/", "/srv/project/html", owner: 'apache', group: 'apache', mount_options: ['share']
```

You can get more details about mount options for "prl_fs" by typing `man mount.prl_fs` in the VM.
