### ISSUE TITLE
Failed to clone ... must enter administrator's credentials

### ISSUE THREAD

**Issue by thesec** [Parallels/vagrant-parallels#178]
Using Parallels v10.1.4 (28883) and Vagrant v1.7.2,
trying to 'vagrant up' I get the following error:

    Command: ["prlctl", "clone", "packer-parallels-iso", "--name", "packer-parallels iso_1425488659628_29612"]

    Stderr: 
    Failed to clone the VM: The operation failed. To perform this operation, you must enter the host OS administrator's credentials.

Resetting the preferences as advised to in https://github.com/Parallels/vagrant-parallels/issues/67 does not resolve the issue.

Looking at the system logs I see

    com.apple.xpc.launchd[1]:
    (com.apple.xpc.launchd.user.501.100006.Aqua)
    Could not read path: path = /Library/LaunchAgents/com.parallels.vm.prl_pcproxy.plist,
    error = 2: No such file or directory

After removal of Vagrant, Parallels and a clean re-install of both and your provider the above plist is still missing in both /Library/... and ~/Library/... and the error remains the same.

What's the cause? How to resolve?

**Comment by thesec** [comment]
*ping* ... anybody ...?

**Comment by legal90** [comment]
@thesec , thanks for a report!
Seems like this issue should be investigated by Parallels team.

Please, reproduce it again and then send a problem-report to Parallels. It can be done via GUI: 'Help -> Report a Problem'.
Then tell me the Report ID (you can post it here or just send an e-mail to mzholobov@parallels.com).

**Comment by thesec** [comment]
Thanks, just sent the report ID to the provided address.

**Comment by legal90** [comment]
@thesec 
Please, refer to https://github.com/Parallels/vagrant-parallels/issues/67#issuecomment-32774326
Option "Require password to: Clone or convert..." should be disabled, e.q. the appropriate checkbox should be empty. You can also do it via command line:
```bash
prlsrvctl set --require-pwd clone-vm:off
```

P.s. I've also detected that we have an issue in `vagrant-parallels`. It should manage this "Require password" settings automatically, but it does not. Will fix it soon

**Comment by thesec** [comment]
Voila, thanks for your help!

**Comment by bramwillemse** [comment]
May I suggest to add this to your support website? I had the same issue using Parallels 'import bootcamp' itself (in the GUI) and couldn't find any other solution to fix this than here!

But I found it, so thanks!
