### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by rmnptrsn** [Parallels/vagrant-parallels#180]
The installation of the plugin fails with this error message:
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

An error occurred while installing nokogiri (1.6.6.2), and Bundler cannot continue.
Make sure that `gem install nokogiri -v '1.6.6.2'` succeeds before bundling.

I've tried to install nokogiri via `gem install nokogiri -v '1.6.6.2'` and it succeeds. After the installation of nokogiri the installation of vagrant-parallels fails with the same error. Any ideas?

**Comment by legal90** [comment]
1) What version of Vagrant are you using? (`vagrant --version`)
2) What other plugins are installed? (`vagrant plugin list`)

**Comment by rmnptrsn** [comment]
Vagrant 1.6.3

vagrant-login (1.0.1, system)
vagrant-share (1.1.1, system)
vagrant-vbguest (0.10.0)

**Comment by legal90** [comment]
I've figured out that it is a known issue of Vagrant 1.6.x: https://github.com/mitchellh/vagrant/issues/3769

Please, upgrade Vagrant to the latest version (1.7.2) and try again. Let us know about the result

**Comment by rmnptrsn** [comment]
Hey, yeah, it worked with vagrant 1.7.2. Thanks a lot!
