### ISSUE TITLE
Shared folder not working

### ISSUE THREAD

**Issue by aklump** [Parallels/vagrant-parallels#181]
I am just getting started with Vagrant and have less than a couple of hours experience.  I have been using Parallels 10 for other reasons and tried to use this provider instead of virtualbox because I read using parallels is more performant than virtualbox.  I'm following the getting started and at this point: http://docs.vagrantup.com/v2/getting-started/synced_folders.html when I vagrant ssh in to the box that I started with vagrant up using the parallels provider and navigate to the sync folder and do an 'ls', I do not see the contents of the root (shared) directory.  When I try to mkdir a file while ssh'ed in I get this error: Cannot allocate memory.  I've pasted the two scenarios below where you can retrace my steps.

If I destroy the box and use the virtualbox provider, the shared folder works as explained in the getting started here: http://docs.vagrantup.com/v2/getting-started/synced_folders.html

        mbp-aaron:backbone aklump$ vagrant version
        Installed Version: 1.7.2

        mbp-aaron:backbone aklump$ vagrant init parallels/centos-6.6
        mbp-aaron:backbone aklump$ vagrant up --provider=parallels
        Bringing machine 'default' up with 'parallels' provider...
        ==> default: Importing base box 'parallels/centos-6.6'...
        ==> default: Checking if box 'parallels/centos-6.6' is up to date...
        ==> default: Setting the name of the VM: backbone_default_1431393292001_81122
        ==> default: Preparing network interfaces based on configuration...
            default: Adapter 0: shared
        ==> default: Clearing any previously set network interfaces...
        ==> default: Forwarding ports...
        ==> default: Setting power consumption mode: "Longer battery life"
        ==> default: Booting VM...
        ==> default: Waiting for machine to boot. This may take a few minutes...
            default: SSH address: 10.211.55.13:22
            default: SSH username: vagrant
            default: SSH auth method: private key
            default: Warning: Connection refused. Retrying...
            default:
            default: Vagrant insecure key detected. Vagrant will automatically replace
            default: this with a newly generated keypair for better security.
            default:
            default: Inserting generated public key within guest...
            default: Removing insecure key from the guest if its present...
            default: Key inserted! Disconnecting and reconnecting using new SSH key...
        ==> default: Machine booted and ready!
        ==> default: Checking for Parallels Tools installed on the VM...
        ==> default: Mounting shared folders...
            default: /vagrant => /Volumes/Data/Users/aklump/Desktop/drupalcon2015/Sandbox/backbone
        mbp-aaron:backbone aklump$ ls
        Vagrantfile      bower_components config.codekit
        mbp-aaron:backbone aklump$ vagrant ssh
        Last login: Wed Apr  1 13:06:28 2015 from 10.211.55.2
        [vagrant@localhost ~]$ ls /vagrant
        uninstall.tool  Vagrant.pkg
        [vagrant@localhost ~]$ mkdir /vagrant/test
        mkdir: cannot create directory `/vagrant/test': Cannot allocate memory
        [vagrant@localhost ~]$

        **********

        mbp-aaron:backbone aklump$ vagrant init hashicorp/precise32
        A `Vagrantfile` has been placed in this directory. You are now
        ready to `vagrant up` your first virtual environment! Please read
        the comments in the Vagrantfile as well as documentation on
        `vagrantup.com` for more information on using Vagrant.
        mbp-aaron:backbone aklump$ vagrant up --provider=virtualbox
        Bringing machine 'default' up with 'virtualbox' provider...
        ==> default: Importing base box 'hashicorp/precise32'...
        ==> default: Matching MAC address for NAT networking...
        ==> default: Checking if box 'hashicorp/precise32' is up to date...
        ==> default: Setting the name of the VM: backbone_default_1431393504104_41618
        ==> default: Clearing any previously set network interfaces...
        ==> default: Preparing network interfaces based on configuration...
            default: Adapter 1: nat
        ==> default: Forwarding ports...
            default: 22 => 2222 (adapter 1)
        ==> default: Booting VM...
        ==> default: Waiting for machine to boot. This may take a few minutes...
            default: SSH address: 127.0.0.1:2222
            default: SSH username: vagrant
            default: SSH auth method: private key
            default:
            default: Vagrant insecure key detected. Vagrant will automatically replace
            default: this with a newly generated keypair for better security.
            default:
            default: Inserting generated public key within guest...
            default: Removing insecure key from the guest if its present...
            default: Key inserted! Disconnecting and reconnecting using new SSH key...
        ==> default: Machine booted and ready!
        ==> default: Checking for guest additions in VM...
            default: The guest additions on this VM do not match the installed version of
            default: VirtualBox! In most cases this is fine, but in rare cases it can
            default: prevent things such as shared folders from working properly. If you see
            default: shared folder errors, please make sure the guest additions within the
            default: virtual machine match the version of VirtualBox you have installed on
            default: your host and reload your VM.
            default:
            default: Guest Additions Version: 4.2.0
            default: VirtualBox Version: 4.3
        ==> default: Mounting shared folders...
            default: /vagrant => /Volumes/Data/Users/aklump/Desktop/drupalcon2015/Sandbox/backbone
        mbp-aaron:backbone aklump$ ls
        Vagrantfile      bower_components config.codekit
        mbp-aaron:backbone aklump$ vagrant ssh
        Welcome to Ubuntu 12.04 LTS (GNU/Linux 3.2.0-23-generic-pae i686)

         * Documentation:  https://help.ubuntu.com/
        New release '14.04.2 LTS' available.
        Run 'do-release-upgrade' to upgrade to it.

        Welcome to your Vagrant-built virtual machine.
        Last login: Fri Sep 14 06:22:31 2012 from 10.0.2.2
        vagrant@precise32:~$ ls /vagrant
        bower_components  config.codekit  Vagrantfile
        vagrant@precise32:~$ mkdir /vagrant/test
        vagrant@precise32:~$ ls /vagrant
        bower_components  config.codekit  test  Vagrantfile
        vagrant@precise32:~$ exit
        logout
        Connection to 127.0.0.1 closed.
        mbp-aaron:backbone aklump$ ls
        Vagrantfile      bower_components config.codekit   test
        mbp-aaron:backbone aklump$

**Comment by aklump** [comment]
I just read this other issue: https://github.com/Parallels/vagrant-parallels/issues/124 and understood that this is most likely a duplicate of that.  I unmounted the share and tried again and the shared folder works as expected.

**Comment by legal90** [comment]
Yes, that's the same as #124.

Seems like we should disable by default these "smart" features of Parallels Desktop in our boxes.
