### ISSUE TITLE
Closing Parallels Desktop suspends vagrant machine

### ISSUE THREAD

**Issue by strider72** [Parallels/vagrant-parallels#183]
Steps to reproduce:

1) "vagrant up" a Vagrant VM running on Parallels.  VM is now running.
2) Open Parallels Desktop.
3) Quit Parallels Desktop
4) Vagrant VM is now suspended.

It seems to me a VM that was running before the Parallels Desktop GUI App was run should continue running separately from that app.  It's an issue if I run my Windows VM for something while Vagrant is running.

**Comment by legal90** [comment]
Unfortunately, it is a common behavior of Parallels Desktop: when you try to do "Parallels Desktop" -> "Quit" (or just press "Cmd+Q") it also stopped all internal Parallels services which are required for virtual machines. Thats why all machines should be stopped or suspended before the quit.
It might be changed in the upcoming releases, but currently GUI quit causes the stop of all internal services.

But it should not cause any problems for different VMs. You can use your Windows VM and close your Vagrant machines' windows (by the red cross in the left top corner). Or shut down your Windows VM by "Actions" -> "Shut Down" and it doesn't affect other VMs.

**Comment by strider72** [comment]
Yes, I suspected it was something that would have to be fixed/changed within Parallels itself (as opposed to the plugin).  Seems that something that was running before the GUI app was started should -- by default anyway -- continue after the GUI app is closed.  Ah well....
