### ISSUE TITLE
Problems with PHPStorm and prlctl since update from Parallels to version 10.2.1 (29006)

### ISSUE THREAD

**Issue by lehnen** [Parallels/vagrant-parallels#184]
Since my update to Parallels version 10.2.1 (29006), PHPStorm can not run my test suites anmyore. It stattes:
Error running All Tests
         java.io.IOException: The provider 'parallels' that was requested to back the machine
         'default' is reporting that it isn't usable on this system. The
         reason is shown below:
         Vagrant could not detect Parallels Desktop! Make sure it is properly installed.
         Vagrant uses the `prlctl` binary that ships with Parallels Desktop, and requires
         this to be available on the PATH. If Parallels Desktop is installed, please find
         the `prlctl` binary and add it to the PATH environmental variable.

May this be a problem with vagrant-parallels ?

**Comment by legal90** [comment]
In Parallels Desktop 10.2.1 `prlctl` binary has been moved from `/usr/bin` to `/usr/local/bin`. But the second path is also available in PATH by default.

@lehnen Is it reproduced only in PHPStorm and works fine in the simple terminal?
If it's not working even in terminal session, then please show the output of these commands: `which prlctl`, `echo $PATH`

**Comment by lehnen** [comment]
Hey legal90 - thanx for quick response ;)
The phpunit is running fine in the terminal sesssion of the vm. On my Mac, I can call the command prtctl.
It is located in /usr/local/bin/ (as you said) an /usr/local/bin is included in the $PATH.

**Comment by legal90** [comment]
So, it means that PHPStorm uses some other $PATH. Try to restart it or refer to PHPStorm issue tracker.

**Comment by legal90** [comment]
Seems like we should add a workaround for this issue, because a lot of customers can be faced with it by some different reasons.

**Comment by legal90** [comment]
Fixed in v1.3.11

@lehnen Please, update the plugin:
```
vagrant plugin update vagrant-parallels
```

**Comment by lehnen** [comment]
@legal90 Yipeeee! It's running ;)
