### ISSUE TITLE
Waiting for the machine to boot

### ISSUE THREAD

**Issue by cisco87** [Parallels/vagrant-parallels#187]
Hello,

I'm new to using vagrant with parallels, I'm trying to get the virtual machine running but when I do `vagrant up` despite I can see the VM to be ready after a while, vagrant doesn't seem to see it the same way. I tried to start it with `vagrant up --debug` and here's the output:

```
INFO subprocess: Starting process: ["/usr/local/bin/prlctl", "list", "c7746e1a-b047-4c79-a5fa-01daf068f11f", "--no-header", "-o", "status"]
DEBUG subprocess: Command not in installer, not touching env vars.
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stdout: running
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 31999
DEBUG subprocess: Exit status: 0


INFO subprocess: Starting process: ["/usr/local/bin/prlctl", "list", "c7746e1a-b047-4c79-a5fa-01daf068f11f", "--no-header", "-o", "status"]
DEBUG subprocess: Command not in installer, not touching env vars.
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stdout: 00:1C:42:EE:67:AA 00:1C:42:0E:D0:77 
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
DEBUG subprocess: Exit status: 0
DEBUG subprocess: stdout: running
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
DEBUG subprocess: Exit status: 0
```

Thanks for any suggestion you may give me

**Comment by legal90** [comment]
Sorry, it's unclear what exactly is going wrong in your case.

Please, ensure that you don't have a collision between some of your local networks (or VPN) with "Shared" network from Parallels Desktop, like here: https://github.com/Parallels/vagrant-parallels/issues/162#issuecomment-68042292

If there is no collisions, please show the output of `netstat -rnf inet` and a full debug log, which can be captured to a file:
```
vagrant up --debug 2>/path/to/debug.log
```

You can post it on something like [Gist](https://gist.github.com/) or send it to me by e-mail.

**Comment by cisco87** [comment]
Hi @legal90 
Many thanks for your reply.

I don't have any shared network configured in the parallels VM, I have just one bridged interface and a host-only network interface, both look to be working correctly, since I can access internet within the VM and I can connect with SSH to the VM using the host-only IP (ping works both ways too).

I created a gist containing the debug.log file: https://gist.github.com/cisco87/7e52c482bd2381450d11

Thanks

**Comment by cisco87** [comment]
Ok @legal90 Apparently the problem is gone, I didn't understand that the shared network interface must be present in order to vagrant-parallels to work properly, I made sure it was configured in the Vagrantfile and now the VM is booting

**Comment by legal90** [comment]
Yes, "Shared" network interface is required to communicate with VM. We have it configured in all our boxes by default.

@cisco87 Could you tell please, how "Shared" interface have been deleted/changed in your case? Did you add `adapter: 0` parameter to the `private_network` configuration?

**Comment by cisco87** [comment]
Hi @legal90 
Yes I did exactly as you said
