### ISSUE TITLE
Customize directive errors in 1.4.0

### ISSUE THREAD

**Issue by joshrivers** [Parallels/vagrant-parallels#197]
When launching the parallels/boot2docker-vagrant-box, I get an error with the 1.4.0 plugin:

/Users/riversj/.vagrant.d/gems/gems/vagrant-parallels-1.4.0/lib/vagrant-parallels/action/customize.rb:29:in `block in call': private method `execute_prlctl' called for #<VagrantPlugins::Parallels::Driver::Meta:0x0000010087ca70> (NoMethodError)
	from /Users/riversj/.vagrant.d/gems/gems/vagrant-parallels-1.4.0/lib/vagrant-parallels/action/customize.rb:22:in `each'
	from /Users/riversj/.vagrant.d/gems/gems/vagrant-parallels-1.4.0/lib/vagrant-parallels/action/customize.rb:22:in `call'

Reverting to 1.3.13 allows the box to be brought up successfully. Did execute_prlctl get made private?

**Comment by legal90** [comment]
@joshrivers Thank you for a report. I'm sorry about this silly failure :(

Fixed in [v1.4.1](https://github.com/Parallels/vagrant-parallels/releases/tag/v1.4.1)

**Comment by joshrivers** [comment]
Silly failures are a sign of humanity. Quick fixes are a sign of excellence. Thanks!
