### ISSUE TITLE
Optimizing the Box Size (prl_disk_tool compact) issue

### ISSUE THREAD

**Issue by alvassin** [Parallels/vagrant-parallels#200]
I want to shrink the hard drives of my vm as much as possible. As i understand, i can replace following code:
```
dd if=/dev/zero of=/EMPTY bs=1M
rm -f /EMPTY
sync
```
using Parallels command `prl_disk_tool compact /path/to/harddisk.hdd`, as described [here](http://parallels.github.io/vagrant-parallels/docs/boxes/base.html).

But i got following error. Could you please tell me, what i am doing wrong?
```
objc[36120]: Class DeallocHook is implemented in both /Applications/Parallels Desktop.app/Contents/Frameworks/ParallelsVirtualizationSDK.framework/Versions/5/libprl_sdk.5.dylib and /Applications/Parallels Desktop.app/Contents/MacOS/prl_disk_tool. One of the two will be used. Which one is undefined.
Invalid option 'harddisk1.hdd'.
```

I tried to specify parameter as `$box/harddisk1.hdd` (folder), as `$box/harddisk1.hdd/harddisk1.hdd`, there is no difference.

**Comment by legal90** [comment]
Sorry, there is a mistake in the docs and it should be fixed. The correct command is:
```
prl_disk_tool compact --hdd /path/to/harddisk.hdd
```
You can also add `--buildmap` option in order to remove all blocks filled with zeroes. It takes an effect for disks managed by LVM (in the most of Linux VMs).
Refer to `man prl_disk_tool` for more details.

**Comment by legal90** [comment]
Fixed.
