### ISSUE TITLE
launchd CPU spike, possibly related to #178 and #67

### ISSUE THREAD

**Issue by lattwood** [Parallels/vagrant-parallels#203]
Parallels Support ID number 71497299.

Lots and lots of attempts to load a non-existent launchd plist whenever I'm performing vagrant actions.

Only hits I could find online relating to the nonexistent com.parallels.vm.prl_pcproxy.plist are in the issues named in the title.

**Comment by legal90** [comment]
Thanks for sending a report! Our folks at Parallels are investigating this issue.

**Comment by lattwood** [comment]
I removed the VirtualBox kexts and reboot, seemed to have gone away. This would be something worth noting, as many people coming to vagrant-parallels would have already been using vagrant with VirtualBox.

**Comment by legal90** [comment]
Hm... That's weird because I have reproduced this issue on the hosts without VirtualBox installed as well. Please, let us know if you will run into this again.

P.s. Messages pulled to syslog.log:
```
Aug 14 14:44:54 hostname.domain sudo[22325]:     root : TTY=unknown ; PWD=/ ; USER=user ; COMMAND=/bin/launchctl load /Library/LaunchAgents/com.parallels.vm.prl_pcproxy.plist
Aug 14 14:44:54 hostname com.apple.xpc.launchd[1] (com.apple.xpc.launchd.user.502.100005.Aqua): Could not read path: path = /Library/LaunchAgents/com.parallels.vm.prl_pcproxy.plist, error = 2: No such file or directory
Aug 14 14:44:54 hostname.domain sudo[22327]:     root : TTY=unknown ; PWD=/ ; USER=user ; COMMAND=/bin/launchctl start com.parallels.vm.prl_pcproxy
```

**Comment by lattwood** [comment]
That was the same one I was getting, but I haven't seen the massive launchd cpu spike anymore. Go figure.
