### ISSUE TITLE
Virtualbox -> Parallels Vagrantfile question

### ISSUE THREAD

**Issue by consciousimages** [Parallels/vagrant-parallels#211]
What is the Parallels version of the following command:

ubuntu.vm.synced_folder "../www-admin", "/var/www", :owner => "www-data", :group => "www-data"

I'm getting:

vm:
* The host path of the shared folder is missing: ../www-admin

The previous line in the Vagrantfile which is simliar is fine:

ubuntu.vm.synced_folder "./app", "/vagrant/app", :owner => "www-data", :group => "www-data"

**Comment by legal90** [comment]
Synced folders for `parallels` provider work the same way as documented here:
https://docs.vagrantup.com/v2/synced-folders/basic_usage.html

> The first parameter is a path to a directory on the host machine. If the path is relative, it is relative to the project root.

The error message is telling obviously that `../www-admin` is not created on your host machine (Mac), so that it could not be shared and the error is shown. 
In the other example, `./app` exist on your host, that's why it works fine.

**Comment by consciousimages** [comment]
Thanks so much@legal90... it's strange.  On my laptop with the VirtualBox, that directory doesn't exist either, and everything worked fine.  But you are absolutely right, adding the directory to my desktop works as it should.

**Comment by legal90** [comment]
@consciousimages You can also add `:create => true` and then directory will be created automatically.
```
ubuntu.vm.synced_folder "../www-admin", "/var/www", :create => true, :owner => "www-data", :group => "www-data"
```

**Comment by consciousimages** [comment]
Thank you @legal90 -- that is perfect.  I'm actually doing a second Vagrantfile if anyone else is going to use Parallels on this project (everyone has used VirtualBox up to now), and that line will save a step.  Appreciate you taking the time to let me know!
