### ISSUE TITLE
Just wondering: performance of Parallels 11 vs. 10?

### ISSUE THREAD

**Issue by dogweather** [Parallels/vagrant-parallels#212]
Can anyone offer anecdotes or benchmarks for Linux as the guest OS on Parallels? It's easy to find Windows benchmarks comparing the Parallels versions, but not with Linux. I'm considering whether to upgrade from 10 to 11.

**Comment by legal90** [comment]
There is some kind of benchmark for Parallels Desktop + Vagrant, but there is no data about version 11 yet: https://github.com/adri/vagrant-virtualbox-vs-parallels

@adri, could you please run your tests with new Parallels Desktop 11?

**Comment by adri** [comment]
There you go https://github.com/adri/vagrant-virtualbox-vs-parallels

**Comment by legal90** [comment]
@adri Thank you very much!

**Comment by dogweather** [comment]
Excellent @adri ! Thank you
