### ISSUE TITLE
Enable linked clones by default

### ISSUE THREAD

**Issue by mkuzmin** [Parallels/vagrant-parallels#213]
Using linked or full clones is not a property of a specific Vagrant box, that's an user preference.

Ideal solution would be enabling linked mode by default, but if you have technical difficulties doing that, please add an environment variable, which I can configure once for all boxes and instances.

**Comment by legal90** [comment]
Yes, I think it's reasonable to enable "Linked Clone" feature by default (when Parallels Desktop 11+ is used). I'll do it the scope of the next plugin release.

For now you can enable it globally for all your Vagrant machines by creating the file `~/.vagrant.d/Vagrantfile` with the content:
```ruby
Vagrant.configure(2) do |config|
  config.vm.provider "parallels" do |prl|
    prl.use_linked_clone = true
  end
end
```
Read more about Vagrantfile load order & merging: https://docs.vagrantup.com/v2/vagrantfile/index.html

**Comment by mkuzmin** [comment]
Wow, I didn't know such global Vagrantfile exists.
It works fine, thanks!

**Comment by legal90** [comment]
Since it could be unexpected behavior for a lot of our users, we've decided to postpone that decision to the major version bump (v2.0.0 or something).


@mkuzmin Thank you for suggestion!
