### ISSUE TITLE
Issue connecting to windows 10 box with vagrant up

### ISSUE THREAD

**Issue by apasquale** [Parallels/vagrant-parallels#217]
Hi,

I have a Windows 10 box which I created using packer. I was able to successfully vagrant up initially, but after a month I wanted to add a new sync folder, so did a vagrant halt followed by a vagrant up.

Now it hangs at:
```
==> vagrant-windows-10: Waiting for machine to boot. This may take a few minutes...
    vagrant-windows-10: WinRM address: 10.211.58.3:5985
    vagrant-windows-10: WinRM username: vagrant
    vagrant-windows-10: WinRM transport: plaintext
```
Until it finally errors with:
```
INFO interface: error: Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.
```

None of my sync folders are available after this.

The strange thing is, while its hung (or after it crashed) I am able to not only see the vm up and running, I can `vagrant ssh` and even `vagrant winrm -c "echo hello"` without an issue.

Things I have tried:
- Reconfiguring winrm (though that works fine with `vagrant winrm`)
- Ensuring networks are set to private
- Turning off the firewall
- Disabling Windows Defender

What I am running on:
- MacBookPro11,3
- OSX Yosemite (though upgraded to ElCapitan yesterday and made no difference to the result)
- Vagrant v1.7.4
- vagrant-parallels v1.5.0
- Parallels v10.3.0

Gist for VagrantFile and logs: https://gist.github.com/apasquale/3b61d1df2dad45024df5

Is there anything else I can try?

**Comment by legal90** [comment]
Looking to the debug log, I see that Vagrant is stuck while trying to execute a powershell command via winrm:
https://github.com/mitchellh/vagrant/blob/bd0626672bdf824356559616c265dca6ac73cad8/plugins/communicators/winrm/communicator.rb#L99

@apasquale Does this command work in your environment? `vagrant winrm -c "hostname"`

P.s. BTW, how much time it spend before Vagrant fails with boot timeout error?

**Comment by apasquale** [comment]
Hi, I have done a bit more testing and found the following:

When I run `vagrant winrm -c "hostname"` after a failed `vagrant up` it responds correctly with:
```
mbp-pas-sms:win10 $ vagrant winrm -c hostname
#< CLIXML
vagrant-10
<Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj><Obj S="progress" RefId="1"><TNRef RefId="0" /><MS><I64 N="SourceId">2</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj><Obj S="progress" RefId="2"><TNRef RefId="0" /><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>
```
but it doesn't seem to properly return from the call (I need to Ctrl + C to exit it)

if I do a `vagrant halt` it doesn't halt the box so I have to kill the process using `ps -ef` and `kill -9` but after that if I do `vagrant suspend` and `vagrant resume` that seems to connect winrm fine and I can run `vagrant winrm -c "hostname"` with a successful return.

RE: your P.s: It spends a long time trying to connect to winrm and I can see the debug logs retrying even after windows is up and running.

I suspect whatever reason that the winrm call doesn't properly return (even though I see the correct respons) is causing this but I have no idea what to do next

**Comment by apasquale** [comment]
A little more info:

After a `vagrant up` with `vagrant winrm -c "hostname"` hanging if I run the following ruby script:
```
require 'winrm'
endpoint = 'http://10.211.58.3:5985/wsman'
winrm = WinRM::WinRMWebService.new(endpoint, :plaintext, :user => 'vagrant', :pass => 'vagrant', :basic_auth_only => true)
winrm.cmd('hostname') do |stdout, stderr|
  STDOUT.print stdout
  STDERR.print stderr
end
```

That seems to run and exit fine

**Comment by apasquale** [comment]
I think I have figured out what's going on here and I have a very hacky workaround...

I started by `vagrant up` a fresh vm from scratch and ran `vagrant winrm -c "hostname"`
I got the following result:
```
mbp-pas-sms:win10 $ vagrant winrm -c "hostname" dev
vagrant-10
mbp-pas-sms:win10 $
```

Which looks much cleaner than the result I was getting earlier (a whole bunch of XML along with the response)

After slowly bringing that VM back up to the same level as my existing vm (running puppet scripts module by module) I found that certain chocolatey packages such as Jump-Location, posh-git and psget were causing my call to `vagrant winrm` to start showing the XML and in some cases the hanging as well.

Switching back to my original VM, I commented out the entire contents of my powershell profile (C:\Users\vagrant\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1) and this made my call to `vagrant winrm` clean again. This also allowed a clean `vagrant up` to happen.

So while I haven't figured out exactly what's causing the workaround, at least I know how to vagrant up again. It's not an issue with vagrant or any plugins so this issue can be closed.

**Comment by StefanScherer** [comment]
@apasquale Thanks for the investigation. I got the same problem on Win2016TP4 and had suspected some windows updates, but I also have `posh-git` installed. Did you come up with a solution, eg. recognizing if it is a winrm session and skip the posh-git initialization?

The problem seems to be the `Start-SshAgent -Quiet` in the posh-git profile.example.ps1 script. This prompts for the passphrase of your SSH key.

My solution is to check for interactive sessions and start the SSH agent only if PowerShell is running from the interactive desktop.

```powershell
If ((Test-Path env:\SESSIONNAME) -And ($env:SESSIONNAME -eq "Console")) {
  Start-SshAgent -Quiet
}
```
