### ISSUE TITLE
Parallels Provider not bringing up network for Ubuntu Trusty VM

### ISSUE THREAD

**Issue by greenaj** [Parallels/vagrant-parallels#218]
I've create a Ubuntu Trusty base virtual box using the default Shared adapter. When vagrant up a new box from this base box the network never goes up and Vagrant is unable SSH into the VM and provisions. This problem has occurred earlier with no clear solution. My CentOS 7 base boxes work just fine. 

Directly logging in through Parallels shows know ip address for eth1. eth0 does not exist

Is this plugin just broken with Ubuntu and this is a known issue? I have resorted to trying to create the base box on Windows with VirtualBox and work on a Windows 7 laptop for now. I'd love to know if I am the only one having this problem. My vagrant-parallels plugin version is 1.5.0 and vagrant version is 1.7.4. The version of Parallels Desktop is 11.0.2. I have wasted several hours over this. Maybe Debian a better choice?

**Comment by legal90** [comment]
We don't have any problem with our official Ubuntu Trusty box:

I guess, that you have the similar case as described here: https://github.com/Parallels/vagrant-parallels/issues/128#issuecomment-50581416
Please ensure that you have removed `/lib/udev/rules.d/75-persistent-net-generator.rules` before the box packaging.

**Comment by greenaj** [comment]
Thanks, I arrived at a similar situation messing up Debian 8 and fixed it be deleting /etc/udev/rules.d/70-persistent-net-generator.rules. It looks like your scripts delete these under /lib/udev. Thanks a lot. This one was hard to find and it looks like I'll need to learn how to use Packer, boxcutter, etc. Thanks.
