### ISSUE TITLE
Replacing colons in sync folder id

### ISSUE THREAD

**Issue by apasquale** [Parallels/vagrant-parallels#220]
I am having an issue creating a synced folder on a windows 10 D:\ drive I have the following in my Vagrantfile

```config.vm.synced_folder "~/code/", "D:/code/"```
When I vagrant up I see:

```dev: D:/code => /Users/myusername/code```
It looks like it creates the folder on the D:\ drive but when I look at it's properties, it is linked to //psf/D:_code. When i run `net use` it shows a share named:

```Y:        \\psf\D_code              Parallels Shared Folders```
So it doesn't match up with the shortcut created in the D:\ drive and I get an error trying to access D:\code

I don't know ruby, but I found the following line in https://github.com/Parallels/vagrant-parallels/blob/master/lib/vagrant-parallels/synced_folder.rb

```id.gsub(/[\/]/,'_').sub(/^_/, '')```

which explains why the '/' became a '_' would it be possible to do something similar for the ':' and align that with what the sync folder is pointing to?

**Comment by legal90** [comment]
@apasquale Thank you for report! 
I've just fixed it. The new release will be published in 1-2 days

**Comment by legal90** [comment]
Fixed in [v1.5.1](https://github.com/Parallels/vagrant-parallels/releases/tag/v1.5.1)

**Comment by apasquale** [comment]
Thanks @legal90 !
