### ISSUE TITLE
Install fail and complain with childprocess install fail

### ISSUE THREAD

**Issue by lijian** [Parallels/vagrant-parallels#231]
Hi,

I'm trying to install the plugin but get following error, `gem install childprocess -v '0.5.8'` execute success independently.

Environment: Mac OS El Capitan (10.11.1)

Installing the 'vagrant-parallels' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

An error occurred while installing childprocess (0.5.8), and Bundler cannot continue.
Make sure that `gem install childprocess -v '0.5.8'` succeeds before bundling.

Thanks,
Lijian

**Comment by legal90** [comment]
@lijian Please provide a debug log. You can get it by this command:
```
vagrant plugin install vagrant-parallels --debug 2>./debug.log
```
It's better to upload the log on [Gist](https://gist.github.com/) or [Pastebin](http://pastebin.com/)

**Comment by lijian** [comment]
Attached debug.log
[debug.log.txt](https://github.com/Parallels/vagrant-parallels/files/36514/debug.log.txt)

**Comment by legal90** [comment]
Thanks. It most likely the issue of core Vagrant and should be reported there: https://github.com/mitchellh/vagrant/

I can only suggest you to clean gems and try again:
```
rm -r ~/.vagrant.d/plugins.json ~/.vagrant.d/gems
vagrant plugin install vagrant-parallels
```

**Comment by lijian** [comment]
Thanks, will try

**Comment by legal90** [comment]
The root of issue: https://github.com/mitchellh/vagrant/issues/6573#issuecomment-159247949
Closed.
