### ISSUE TITLE
Box doesn't start after OSX update 10.11.2

### ISSUE THREAD

**Issue by smichaelsen** [Parallels/vagrant-parallels#237]
After updating my OSX to 10.11.2 my box doesn't come up anymore. I get the following error:

    ==> default: Preparing network interfaces based on configuration...
        default: Adapter 0: shared
        default: Adapter 1: hostonly
    ==> default: Clearing any previously set network interfaces...
    ==> default: Forwarding ports...
        default: 22 => 6260
    There was an error while command execution. The command and stderr is shown below.

    Command: ["/usr/local/bin/prlsrvctl", "net", "set", "Shared", "--nat-tcp-add", "tcp6260,6260,06e3f2ae-4ca1-4982-b5ac-7e0418fac412,22"]

    Stderr: Failed to update Virtual Network Shared: The IP address of the Parallels network adapter has not been changed. There was a failure changing the IP address of the Parallels network adapter. The other network parameters have been modified successfully.

Since then I

* upgraded Parallels from 10 to 11 Pro (cost me 119,83€)
* completely reinstalled parallels
* updated the vagrant-parallels plugin
* rebooted by host machine
* removed the box with the Parallels GUI (because `vagrant destroy` resulted in the same error)

the result is still the same.

I'd appreciate any ideas!

**Comment by mblaschke** [comment]
Try to reset all networks in "network" tab in Parallels Preferences.

**Comment by smichaelsen** [comment]
Result is still the same. Thx for the hint.

**Comment by mblaschke** [comment]
Maybe reboot after resetting network defaults?

**Comment by smichaelsen** [comment]
Doesn't help either.

**Comment by dskr99** [comment]
@smichaelsen Hi, please enable detailed logging (menu Paralels -> Preferences -> Advanced), reproduce the issue and send a problem report, post here a problem report number. Disable the detailed logging then.

**Comment by smichaelsen** [comment]
@dskr99 Report ID: 83232069

**Comment by dskr99** [comment]
I believe that something is corrupted within Mac OS X, since I see the error at boot of OS and while loading almost any network drivers in the system.log:

Dec 11 07:40:49 Sebastians-MacBook-Air-2 com.apple.kextd[51]: ERROR: invalid signature for com.apple.iokit.IONetworkingFamily, will not load
Dec 11 07:40:49 Sebastians-MacBook-Air-2 com.apple.kextd[51]: Signature failure in dependencies for kext load request.

This prevents parallels networking from fully functioned start. I think that you should try to reinstall the Mac OS from recovery partition.

**Comment by dskr99** [comment]
@smichaelsen As another possible solution (without repairing corrupted IONetworkingFamily), you can try to go to the parallels network editor (Parallels -> Preferences -> Network) and disable option "Connect Mac to this network" for all parallels network. I'm not sure that this will help, but it is worth to try, if you don't want to repair OS.

**Comment by smichaelsen** [comment]
@dskr99 These were already checked per default. http://shots.michaelsen.io/MFD2
Then maybe I'll reinstall my OSX over the weekend. Thanks for your support!

**Comment by legal90** [comment]
>  and disable option "Connect Mac to this network" for all parallels network."
@dskr99 Even if it helps, this option shouldn't be disabled for "Shared" network, because in this case Vagrant couldn't access the VM.

**Comment by smichaelsen** [comment]
Reinstalling OSX fixed the problem for me. Thanks for your support, @dskr99 and others!
