### ISSUE TITLE
vagrant parallels provider fails to bring up new machine

### ISSUE THREAD

**Issue by stevs986** [Parallels/vagrant-parallels#238]
OS X Version: El Capitan 10.11.2
Vagrant version: 1.7.4
Vagrant parallels plugin version: vagrant-parallels (1.5.1)

Vagrant file is really simple:
```
Vagrant.configure(2) do |config|
  config.vm.box = "parallels/ubuntu-14.04"
end
```

I got this error:
`/Users/[]/.vagrant.d/gems/gems/vagrant-nfs_guest-0.1.7/lib/vagrant-nfs_guest/providers/parallels/cap/nfs_settings.rb:7:in `nfs_settings': undefined method `provider' for nil:NilClass (NoMethodError)`

**Comment by legal90** [comment]
That's an issue of "vagrant-nfs_guest" plugin. Please, report it there: https://github.com/Learnosity/vagrant-nfs_guest/issues

I see that there is a mistake here:
https://github.com/Learnosity/vagrant-nfs_guest/blob/master/lib/vagrant-nfs_guest/providers/parallels/cap/nfs_settings.rb#L7-L8
`@machine` should be replaced with `machine`. But I couldn't test it and send a pull request there right now.

**Comment by stevs986** [comment]
Thanks @legal90

**Comment by alangarf** [comment]
Yup, my bad. Cut and paste error. :( Not having parallels to test it with it was a shot in the dark.

Hopefully v0.1.8 should fix it :+1:
