### ISSUE TITLE
vagrant destroy doesn't seem to remove the box from Parallels Desktop

### ISSUE THREAD

**Issue by wizonesolutions** [Parallels/vagrant-parallels#246]
Vagrant 1.8.1, vagrant-parallels 1.6.1, latest PD11 update on El Capitan.

I can get more detailed steps to reproduce for this if you like.

Using the `dev` branch of https://github.com/hashbangcode/vlad, create a simple settings file (copy `vlad_guts/example.settings.yml` to `../settings/vlad_settings.yml`.

`vagrant up --provider=parallels`

`vagrant destroy -f`

`vagrant up --provider=parallels`

Output like this appears:

````
==> myvm: No machine id, nothing removed from /etc/hosts
==> myvm: Registering VM image from the base box 'bento/ubuntu-14.04'...
==> myvm: Cloning new virtual machine...
==> myvm: Unregistering the box VM image...
==> myvm: Setting the default configuration for VM...
==> myvm: Checking if box 'bento/ubuntu-14.04' is up to date...
==> myvm: A newer version of the box 'bento/ubuntu-14.04' is available! You currently
==> myvm: have version '2.2.2'. The latest is version '2.2.3'. Run
==> myvm: `vagrant box update` to update.
Parallels Desktop virtual machine with the name 'myvm_vlad' already exists.
Please use another name or delete the machine with the existing
name, and try again.
````

Workaround is to manually delete the box in Parallels Desktop Control Center.

**Comment by legal90** [comment]
@wizonesolutions Sorry, I can't reproduce it due to https://github.com/hashbangcode/vlad/issues/324
Please, show the debug output while destroy, `vagrant destroy -f --debug`. You can upload it to Gist, Pastebin or send it to my e-mail. 
Thanks.

**Comment by legal90** [comment]
@wizonesolutions Is the issue still actual?

**Comment by wizonesolutions** [comment]
I don't think so. I think it was because Vlad had moved the `.vagrant` directory. Can't recall having encountered it again.
