### ISSUE TITLE
Ubuntu: Don't use LTS Hardware Enablement Stack

### ISSUE THREAD

**Issue by byronclark** [Parallels/vagrant-parallels#247]
The current Parallels Ubuntu 14.04 boxes use the LTS Hardware Enablement Stack (https://wiki.ubuntu.com/Kernel/LTSEnablementStack).

Usually this wouldn't be a big issue, but there's a fairly nasty bug that affects NFS and the `install(1)` command: https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1445664.

I'd love to see these boxes built without the LTS Hardware Enablement Stack as recommended by Ubuntu for cloud and virtual images.

**Comment by legal90** [comment]
Hi @byronclark,
Thank you for pointing on this. We use public templates from bento project to build our boxes: https://github.com/chef/bento
So, I think we should to discuss it with Bento maintainers.

@cheeseplus @yzl What do you think about that issue? Should  "LTS Hardware Enablement Stack" be disabled in bento templates?

**Comment by legal90** [comment]
Closed in favor of https://github.com/chef/bento/issues/529
