### ISSUE TITLE
Failed to parse the JSON string

### ISSUE THREAD

**Issue by joseconti** [Parallels/vagrant-parallels#249]
JSON string is shown below:

{"ID": "15b99cca-d87b-4370-9584-95891a4b5dd8","Hostname": "127.0.0.1","Version": "Desktop 11.1.2-32408","OS": "Mac OS X 10.11.3(15D21)","Started as service": "off","VM home": "\/Users\/joseconticalveras\/Documents\/Parallels","Memory limit": {"mode": "auto"},"Minimal security level": "low","Manage settings for new users": "allow","CEP mechanism": "off","Backup path": "\/Users\/Shared\/Parallels\/Backups","Backup temporary directory": "","Backup timeout": 3600,"Default encryption plugin": "<parallels-default-plugin>","Verbose log": "off","Allow mobile clients": "off","Proxy connection state": "disconnected","Direct connection": "off","Log rotation": "on","Advanced security mode": "off","Proxy manager URL": "https:\/\/pax-manager.myparallels.com\/xmlrpc\/rpc.do","Web portal domain": "parallels.com","Host ID": "{9a86d6c0-95aa-5781-bb99-37e0fb479ffd}","Allow attach screenshots": "on","Require password to": [\"remove-vm\"],"License": {"state": "valid","key": "011-27598-43896-24035-20564-38465;248-09854-13236-23954-20564-38467;010-18200-64852-23826-22612-38464;078-26433-26225-23941-21332-38465","restricted": "false"},"Hardware Id": "{9a86d6c0-95aa-5781-bb99-37e0fb479ffd}","Signed In": "yes","Hardware info": {"/dev/disk0": {"name": "TS480GJDM500 (disk0)","type": "hdd"},"/dev/disk0s1": {"name": "EFI System Partition","type": "hdd-part"},"/dev/disk0s2": {"name": "Macintosh HD","type": "hdd-part"},"/dev/disk0s3": {"name": "Recovery HD","type": "hdd-part"},"Default CD/DVD-ROM": {"name": "Default CD\/DVD-ROM","type": "cdrom"},"en0": {"name": "Wi-Fi","type": "net"},"en1": {"name": "en1","type": "net"},"p2p0": {"name": "p2p0","type": "net"},"bridge0": {"name": "Thunderbolt Bridge","type": "net"},"vnic0": {"name": "vnic0","type": "net"},"vnic1": {"name": "vnic1","type": "net"},"fd110000|05ac|8404|high|--|000000000310": {"name": "Apple Internal Memory Card Reader","type": "usb"},"fa200000|05ac|850a|high|--|CCGB6F1214DL8LFX": {"name": "Apple FaceTime Camera (Built-in)","type": "usb"},"fa120000|05ac|024d|full|KM|Empty": {"name": "Apple Internal Keyboard \/ Trackpad","type": "usb"},"fa113000|05ac|821f|full|--|Empty": {"name": "Apple Bluetooth USB Host Controller","type": "usb"},"/dev/cu.Bluetooth-Incoming-Port": {"name": "\/dev\/cu.Bluetooth-Incoming-Port","type": "serial"},"/dev/cu.iPhonedeJoseContiJr-Wir": {"name": "\/dev\/cu.iPhonedeJoseContiJr-Wir","type": "serial"}}}

**Comment by legal90** [comment]
Duplication of #242.
Please, follow the instruction here: https://github.com/Parallels/vagrant-parallels/issues/242#issuecomment-170844068

**Comment by legal90** [comment]
That issue has been fixed in Parallels Desktop 11.1.3
Please, upgrade: http://kb.parallels.com/111603
