### ISSUE TITLE
The installed version of Vagrant Parallels plugin is only compatible with Vagrant 1.8+

### ISSUE THREAD

**Issue by ssbarnea** [Parallels/vagrant-parallels#250]
I installed the parallels plugin but it seems that it was not updated to work with recent versions of vagrant.

I am not really surprised as I doubt there are many developers still considering using Parallels since the introduction of the "pro/business" version.

**Comment by legal90** [comment]
At the moment the latest version of Vagrant is 1.8.1 and the `vagrant-parallels` v1.6.1 works fine with it.
@ssbarnea Please ensure that you use Vagrant 1.8.0 or higher
```
vagrant --version
```

**Comment by legal90** [comment]
I close it as invalid.
Let us know if you still have some issues with running `vagrant-parallels` with the latest Vagrant
