### ISSUE TITLE
Virtual machine doesn't initialize network interfaces

### ISSUE THREAD

**Issue by majksner** [Parallels/vagrant-parallels#251]
I think this is not an issue with vagrant provider but with Parallels itself.

I regularly after work do `vagrant halt` tomorrow when get to work and I do `vagrant up` machine boot but no network interfaces are initialized and I have to do `vagrant destroy` and then `vagrant up` to get it working.

![screen shot 2016-02-23 at 8 23 31 am](https://cloud.githubusercontent.com/assets/512355/13244479/c16f0d72-da06-11e5-9043-3866639e65bd.png)

Update: this was happening it last few versions of Parallels even latest (11.1.3)

**Comment by legal90** [comment]
@majksner 
- Do you use a custom box, or a public box? Which one?
- Does that issue happen with one of our public boxes? https://github.com/Parallels/vagrant-parallels/wiki/Available-Vagrant-Boxes

**Comment by majksner** [comment]
I do use https://github.com/boxcutter/ubuntu

I have not tried if it happens with your public boxes. Also I'd like to mention that box works fine for a 20 days for example and then it just stops to initialize network interface.

**Comment by legal90** [comment]
> Also I'd like to mention that box works fine for a 20 days for example and then it just stops to initialize network interface.

It most likely that some network configuration was changed from the VM (guest) side, or from the host side (in VM settings). Please, double check that:
* your VM's first network adapter is configured to `Shared` ("Configure" -> "Hardware" -> "Network 1" -> "Source: Shared"). [doc link](http://download.parallels.com/desktop/v11/docs/en_US/Parallels%20Desktop%20User's%20Guide/33138.htm)
* from the guest side the network adapter is configured properly. It should get an IP from DHCP:
```
$ cat /etc/network/interfaces
# This file describes the network interfaces available on your system
# and how to activate them. For more information, see interfaces(5).

# The loopback network interface
auto lo
iface lo inet loopback

# The primary network interface
auto eth0
iface eth0 inet dhcp
# This is an autoconfigured IPv6 interface
iface eth0 inet6 auto
pre-up sleep 2
```
* other VM's on your host works fine and get an IP without any issues

**Comment by majksner** [comment]
Everything is configured properly in the Parallels, I personally don't open Parallels at all, I'm using vagrant to build and start machines.

This is output I have on cat commands

```
# This file describes the network interfaces available on your system
# and how to activate them. For more information, see interfaces(5).

# The loopback network interface
auto lo
iface lo inet loopback

# The primary network interface
auto eth0
iface eth0 inet dhcp
# This is an autoconfigured IPv6 interface
iface eth0 inet6 auto
pre-up sleep 2
#VAGRANT-BEGIN
# The contents below are automatically generated by Vagrant. Do not modify.
auto eth1
iface eth1 inet static
      address 192.168.33.10
      netmask 255.255.255.0
#VAGRANT-END
```

It is automatically generated by boxcutter build script.

**Comment by majksner** [comment]
This is how ifconfig looks like when everything works fine.

```
vagrant@vagrant-renhead:~$ ifconfig
eth0      Link encap:Ethernet  HWaddr 00:1c:42:f0:33:42
          inet addr:10.211.55.130  Bcast:10.211.55.255  Mask:255.255.255.0
          inet6 addr: fe80::21c:42ff:fef0:3342/64 Scope:Link
          inet6 addr: fdb2:2c26:f4e4:0:21c:42ff:fef0:3342/64 Scope:Global
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:71498 errors:0 dropped:0 overruns:0 frame:0
          TX packets:68354 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:20050547 (20.0 MB)  TX bytes:7138059 (7.1 MB)

eth1      Link encap:Ethernet  HWaddr 00:1c:42:60:88:40
          inet addr:192.168.33.10  Bcast:192.168.33.255  Mask:255.255.255.0
          inet6 addr: fdb2:2c26:f4e4:2:21c:42ff:fe60:8840/64 Scope:Global
          inet6 addr: fe80::21c:42ff:fe60:8840/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:63376 errors:0 dropped:0 overruns:0 frame:0
          TX packets:24130 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:5387589 (5.3 MB)  TX bytes:325098655 (325.0 MB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:213414 errors:0 dropped:0 overruns:0 frame:0
          TX packets:213414 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:75399552 (75.3 MB)  TX bytes:75399552 (75.3 MB)
```

When it stops working eth0 is not there. only eth1 and lo.

Hope it helps.

**Comment by legal90** [comment]
Provided outputs are absolutely OK - everything works fine there. 
So, you should to check the network configuration next time, when the issue will be reproduced again.

As I've understood, you get `eth0` disappeared sometimes after the VM restart. And yet another restart (`vagrant reload`) doesn't solve it, do it?

IMO, if other VMs still work fine, it means that something wrong was done in that particular VM. Probably, some script or command have previously reconfigured a network in the guest.
Just to clarify: in Vagrant use-cases Parallels Desktop doesn't configure VM's network, only Vagrant does it.

I can try to help you if you provide a debug output of vagrant command which causes this issue:
```
vagrant up --debug 2> ./debug.log
# or 
vagrant reload --debug 2> ./debug.log
```
You can [gist](https://gist.github.com/) it or just send it to me by e-mail.

**Comment by majksner** [comment]
I don't use `vagrant reload`, but I'll try that. I usually do `vagrant halt` when I'm done with the work and then `vagrant up` when I start working. I don't have any other VMs used so I can't tell you that.

Thanks for the info. I'll post gist when I encounter issue again.

**Comment by majksner** [comment]
Hi @legal90 I've encountered issue again, I've send you a gist to your email.

**Comment by legal90** [comment]
@majksner Thanks. The provided log-file tells that everything was done right from the Vagrant side - network interfaces are configured correctly, so it is expected that VM should up with an IP leased by DHCP.
Seems like this issue should be investigated from the guest side - why the eth0 interface is not configured automatically by DHCP in that particular case.

Sorry, I can't reproduce it because you use a custom private box. The clear `boxcutter/ubuntu-1404` works fine for me.

If you can't investigate it by yourself, please send a Problem Report to Parallels:
1) Turn on detailed logging in Parallels Desktop (Parallels Desktop -> Preferences -> Advanced -> select "Use detailed log messages"
2) Reproduce the issue
3) Send a problem report (select VM window  -> Help -> Send technical data) and the turn off detailed logging
4) Post a Report ID here (or send it to me by e-mail)

P.s. I's also important to know - does VM restart solves the problem or not? You can just stop the VM via GUI and try to run `vagrant up` again.

**Comment by majksner** [comment]
I doesn't happen all the time, sometimes it happens after few days, sometimes after 20 days. There is no pattern. At least I don't see any pattern. I didn't try to shutdown machine via GUI, I'll try and let you know. Thanks anyway.

**Comment by legal90** [comment]
I'm closing this issue due to the long period of inactivity. If it is still actual - feel free to create a new one.
