### ISSUE TITLE
boot2docker v1.10.0 can not be fetched

### ISSUE THREAD

**Issue by jbjoret** [Parallels/vagrant-parallels#252]
At first I though something was broken on my Mac. But then I realized that it is only version 1.10.0 that is having an issue. I would appreciate a fix, or a newer 1.10.2 version :)

$ vagrant box add --box-version 1.9.1 parallels/boot2docker
==> box: Loading metadata for box 'parallels/boot2docker'
    box: URL: https://atlas.hashicorp.com/parallels/boot2docker
==> box: Adding box 'parallels/boot2docker' (v1.9.1) for provider: parallels
    box: Downloading: https://atlas.hashicorp.com/parallels/boxes/boot2docker/versions/1.9.1/providers/parallels.box
==> box: Successfully added box 'parallels/boot2docker' (v1.9.1) for 'parallels'!

As you can see works perfectly. Then ...

$ vagrant box add --box-version 1.10.0 parallels/boot2docker
==> box: Loading metadata for box 'parallels/boot2docker'
    box: URL: https://atlas.hashicorp.com/parallels/boot2docker
==> box: Adding box 'parallels/boot2docker' (v1.10.0) for provider: parallels
    box: Downloading: https://atlas.hashicorp.com/parallels/boxes/boot2docker/versions/1.10.0/providers/parallels.box
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Unknown SSL protocol error in connection to atlas.hashicorp.com%20https:443 
$

**Comment by legal90** [comment]
@jbjoret Thank you for pointing on it!
I've just fixed the link. Please, try again

**Comment by jbjoret** [comment]
Very nice, it is working :). Thank you
