### ISSUE TITLE
`vagrant snapshot` fails with a not supported error

### ISSUE THREAD

**Issue by travisn** [Parallels/vagrant-parallels#253]
Running Vagrant 1.8.1 and the parallels provider 1.6.1, when I try to take a snapshot I get the error 

> Vagrant attempted to call the action 'snapshot_save' on the provider 'Parallels (b34a2a46-f78f-4ecc-91ec-d9935968cee8)', but this provider doesn't support this action. This is probably a bug in either the provider or the plugin calling this action, and should be reported.

Am I missing something or can support be added for snapshots? Thanks!

**Comment by legal90** [comment]
@travisn Thank you for pointing on this issue!
This is definitely my bad - I've implemented action classes in #228, but haven't defined them in action list. :disappointed_relieved: 
The fix is coming soon...

**Comment by legal90** [comment]
@travisn The fix has been released in [v1.6.2](https://github.com/Parallels/vagrant-parallels/releases/tag/v1.6.2)

**Comment by travisn** [comment]
Great, thanks for the quick turnaround! I am able to take a snapshot now.
