### ISSUE TITLE
Kernel issues when running vagrant-parallels

### ISSUE THREAD

**Issue by nathanielatom** [Parallels/vagrant-parallels#267]
Whenever I have vagrant-parallels running on OS X 10.11.5 it causes extreme kernel issues: kernel_task consumes several thousand % CPU and several GB of memory according to activity monitor, making my host OS unusable due to extreme lag (even keyboard I/O gets skipped). This happens after a fresh reboot, running nothing but vagrant-parallels. As far as I can tell it does not happen otherwise, even running much beefier virtual machines with parallels desktop. Attached is my `/Library/Logs/parallels.log` file.

[parallels.log.zip](https://github.com/Parallels/vagrant-parallels/files/355193/parallels.log.zip)

**Comment by legal90** [comment]
Hi @nathanielatom,
Seems like you have experienced an issue which should be investigated by Parallels kernel engineers. Unfortunately, `/Library/Logs/parallels.log` is not enough in this case. Please, reproduce that issue again and:
1) Create a Problem Report (http://kb.parallels.com/eu/9058) and provide the report ID you receive;
2) Run `sudo spindump` and attach the collected report.

You can send this data to me personally, via e-mail (in profile). Thank you!

**Comment by legal90** [comment]
@nathanielatom Any updates on this?

**Comment by legal90** [comment]
I close this issue due to lack of response. 
If you run into this again, feel free to file a new issue or follow up this one.
