### ISSUE TITLE
prlsrvctl is missing

### ISSUE THREAD

**Issue by Arwany** [Parallels/vagrant-parallels#275]
Hi, where do I find this tool: prlsrvctl, it appears it is missing (or at least in my Mac).
I use Mac 10.11
Thanks

**Comment by legal90** [comment]
Hi @Arwany,
`prlsrvctl` and `prlctl` are CLI utilities bundled with Parallels Desktop for Mac.
By default they are installed (as symlinks) to `/usr/local/bin/`. Also, you can find them in Parallels Desktop app bundle:
- `/Applications/Parallels Desktop.app/Contents/MacOS/prlctl`
- `/Applications/Parallels Desktop.app/Contents/MacOS/prlsrvctl`

If these utilities are not available on your system, then I'd recommend you to re-install Parallels Desktop. That shouldn't affect your existing VMs.

If you have any troubles with using our Vagrant provider, please show the error message you've got from Vagrant.

**Comment by Arwany** [comment]
Thanks a lot.
