### ISSUE TITLE
Installing the plugin seems to have no effect

### ISSUE THREAD

**Issue by erquhart** [Parallels/vagrant-parallels#276]
I'm running Vagrant 1.8.6 with vagrant-parallels 1.6.3, attempting to initialize the parallels/ubuntu-14.04 box. Even with the --provider flag set, Vagrant always attempts to open VirtualBox with the standard message:

```shell
The provider 'virtualbox' that was requested to back the machine
'default' is reporting that it isn't usable on this system. The
reason is shown below:

Vagrant could not detect VirtualBox! Make sure VirtualBox is properly installed.
Vagrant uses the `VBoxManage` binary that ships with VirtualBox, and requires
this to be available on the PATH. If VirtualBox is installed, please find the
`VBoxManage` binary and add it to the PATH environmental variable.
```

I don't want to download VirtualBox.

Know anything?

**Comment by legal90** [comment]
Hi @erquhart,
It seems like the provider name is overridden somewhere else. Could you please provide the debug output (via Gist)?
```
vagrant init parallels/ubuntu-14.04
vagrant up --provider parallels --debug 2>./debug.log
```

**Comment by erquhart** [comment]
Thanks @legal90, log attached.

[debug.log.txt](https://github.com/Parallels/vagrant-parallels/files/503125/debug.log.txt)

**Comment by legal90** [comment]
@erquhart 
> DEBUG command: Finding machine that match name: default
 INFO command: Active machine found with name default. Using provider: virtualbox

These lines mean that vagrant has detected the previously created VM with provider "virtualbox". Vagrant caches this state in directory `.vagrant/` folder, relative to the folder where the Vagrantfile is. So you can clean up it this way:
```
# Clean up the current state
vagrant destroy -f
rm -rf ./.vagrant

# Try again
vagrant up --provider parallels
```

**Comment by erquhart** [comment]
Boy do I feel silly. Yep, working now. Thank you for your help on this!
