### ISSUE TITLE
Using existent Parallels VM

### ISSUE THREAD

**Issue by NicolaeCasir** [Parallels/vagrant-parallels#278]
Hi can i use vagrant on existen Linux mint from parallels? I need this!

**Comment by legal90** [comment]
Hm.. That sounds really strange, but you can do by following these steps:
**1)** Get the UUID of the existing VM
```console
$ prlctl list -a
UUID                                    STATUS       IP_ADDR         NAME
{b67184ab-29c5-43f2-91ed-cda6164f9f46}  stopped    -               my-existing-vm
```

**2)** Create a Vagrantfile in any empty folder. Vagrant requires at least `config.vm.box` to be specified, but you might also need to specify proper [SSH settings](https://www.vagrantup.com/docs/vagrantfile/ssh_settings.html), such as `config.ssh.username` and `config.ssh.password` (or `config.ssh.private_key_path`):
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "parallels/ubuntu-14.04"
  config.ssh.username = "vagrant"
  config.ssh.private_key_path = "/path/to/id_rsa"
end
```

**3)** Staying in the dir where Vagrantfile is placed, create a special dir and then put your VM UUID to the file `id`:
```console
$ mkdir -p .vagrant/machines/default/parallels
$ echo 'b67184ab-29c5-43f2-91ed-cda6164f9f46' > .vagrant/machines/default/parallels/id
```

That's it! Now you can use `vagrant` commands to manage your VM:
```console
$ vagrant status
Current machine states:

default                   stopped (parallels)

The VM is stopped. To start the VM, simply run `vagrant up`
```
