### ISSUE TITLE
Support for Parallels 12

### ISSUE THREAD

**Issue by relengine** [Parallels/vagrant-parallels#279]
Hi,

Wondering when Parallels 12 will be supported. I see it's not listed at http://parallels.github.io/vagrant-parallels/ and trying to use the vagrant plugin fails during network setup.

Env:
- macOS Sierra 10.12.1
- parallels 12.0.2
- vagrant 1.8.6
- vagrant-parallels 1.6.3

```
$ vagrant init parallels/debian-8.5
...
$ vagrant up
Bringing machine 'default' up with 'parallels' provider...
==> default: Box 'parallels/debian-8.5' could not be found. Attempting to find and install...
    default: Box Provider: parallels
    default: Box Version: >= 0
==> default: Loading metadata for box 'parallels/debian-8.5'
    default: URL: https://atlas.hashicorp.com/parallels/debian-8.5
==> default: Adding box 'parallels/debian-8.5' (v2.0.2) for provider: parallels
    default: Downloading: https://atlas.hashicorp.com/parallels/boxes/debian-8.5/versions/2.0.2/providers/parallels.box
==> default: Successfully added box 'parallels/debian-8.5' (v2.0.2) for 'parallels'!
==> default: Registering VM image from the base box 'parallels/debian-8.5'...
==> default: Cloning new virtual machine...
==> default: Unregistering the box VM image...
==> default: Setting the default configuration for VM...
==> default: Checking if box 'parallels/debian-8.5' is up to date...
==> default: Connecting host to Shared network...
There was an error while command execution. The command and stderr is shown below.

Command: ["/usr/local/bin/prlsrvctl", "net", "set", "Shared", "--connect-host-to-net", "on"]

Stderr: Failed to update Virtual Network Shared: The IP address of the Parallels network adapter has not been changed. There was a failure changing the IP address of the Parallels network adapter. The other network parameters have been modified successfully.
```

The same results happened for the `parallels/centos-7.2` box:
```
$ vagrant init parallels/centos-7.2
...
$ vagrant up
...
==> default: Checking if box 'parallels/centos-7.2' is up to date...
==> default: Connecting host to Shared network...
There was an error while command execution. The command and stderr is shown below.

Command: ["/usr/local/bin/prlsrvctl", "net", "set", "Shared", "--connect-host-to-net", "on"]

Stderr: Failed to update Virtual Network Shared: The IP address of the Parallels network adapter has not been changed. There was a failure changing the IP address of the Parallels network adapter. The other network parameters have been modified successfully.
```

Thanks

**Comment by dskr99** [comment]
Hi, could you please reproduce the problem and send a problem report: menu Parallels Desktop -> Help -> Send technical data
and post here its number

**Comment by legal90** [comment]
@relengine Yes, the compatibility with Parallels Desktop 12 is officially supported. It was implemented in https://github.com/Parallels/vagrant-parallels/pull/271.
But yeah, information on our documentation site is a bit out-of-date. I'll re-render these pages and update them soon. Thanks for pointing on this!

About the issue you've faced with: this is actually not related to the Vagrant provider and caused by some problem with Parallels Desktop on your host. 
@dskr99 is one of Parallels engineers, so please send us a Problem Report, as he has mentioned. That will allow us to investigate the problem and help you to solve it.
Thanks!

**Comment by relengine** [comment]
Thanks for the quick feedback! Glad it's supported. I generated and submitted the report, the ID is 125879758

Unfortunately, I'm unable to reproduce the issue now. I tried for both of the same 2 boxes that failed for me before and I've tried a new box that hadn't already been downloaded. In all cases things work great. I'm not aware of any differences as to why it'd fail then and work now. Feel free to close the issue and if it comes back I'll create a new ticket and publish a new technical data report. Thanks again!

**Comment by legal90** [comment]
The provider documentation site has been updated. Now it has an information about Parallels Desktop 12 support

**Comment by mikebronner** [comment]
Hi @legal90 and @dskr99:
I just saw this issue arise again today under High Sierra Beta 4. I submitted a report ID 199237852. Is there a work-around or change I can make on my end to get running again? Thanks! :)

**Comment by romankulikov** [comment]
> Is there a work-around or change I can make on my end to get running again?
We have serious issues with 10.13 Beta 4. Disabling System Integrity Protection should help.

**Comment by mikebronner** [comment]
Thanks @romankulikov ! I turned off SIP, but still get the following error. I know you guys are working hard on this, but am still getting this error when trying to bring up Laravel Homestead using the latest version of Parallels headless:

```
There was an error while command execution. The command and stderr is shown below.

Command: ["/usr/local/bin/prlctl", "set", "6313fe4a-efc0-483c-b10a-11ebb22b5927", "--shf-host-del", "home_vagrant_Sites"]

Stderr: failed to apply settings Unable to complete the operation for the virtual machine "homestead-7". The virtual machine ID is invalid. To resolve the problem, remove the virtual machine from the list and add it again.
Failed to configure the virtual machine.
```

Where should I keep an eye out for the status on this issue? Thanks again!

**Comment by romankulikov** [comment]
> I turned off SIP, but still get the following error.

@mikebronner, can you please send us another problem report with reproduced issue and disabled SIP?

> Where should I keep an eye out for the status on this issue?

From my point it's better to file a separate ticket here.
