### ISSUE TITLE
Unable to install parallels/ubuntu boxes.

### ISSUE THREAD

**Issue by boucher** [Parallels/vagrant-parallels#280]
Any attempt to pull in boxes is failing for me. Here's a sample output:

```
$ vagrant box add parallels/ubuntu-16.04
The box 'parallels/ubuntu-16.04' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://atlas.hashicorp.com/parallels/ubuntu-16.04"]
Error: 
```

Running Vagrant 1.8.7, Parallels 12, and Vagrant Parallels 1.7.0.

**Comment by legal90** [comment]
Hi @boucher! Do you use Vagrant v1.8.7?
If yes, then it is a known issue of Vagrant. Please, refer to https://github.com/mitchellh/vagrant/issues/7969
There is a workaround mentioned and it should help you.

**Comment by boucher** [comment]
Thanks, that's it. Did as suggested in the comments:

```sudo rm -rf /opt/vagrant/embedded/bin/curl```
