### ISSUE TITLE
vagrant up is running very slowly

### ISSUE THREAD

**Issue by wizonesolutions** [Parallels/vagrant-parallels#289]
For some reason, `vagrant up` is running really slowly.

VMs tend to get stuck on the step setting the name or registering the VM (or it at least takes really long). This might be related to the Parallels Desktop update I installed recently.

Example debug output:

```
==> vm-name: Registering VM image from the base box 'bento/ubuntu-14.04'...
 INFO subprocess: Starting process: ["/usr/local/bin/prlctl", "register", "/Users/kevin/.vagrant.d/boxes/bento-VAGRANTSLASH-ubuntu-14.04/2.3.1/parallels/ubuntu-14.04-amd64.pvm", "--preserve-uuid"]
DEBUG subprocess: Command not in installer, not touching env vars.
 INFO subprocess: Command not in installer, restoring original environment...
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stdout: Register the VM...
DEBUG subprocess: stdout: The VM has been successfully registered.
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
DEBUG subprocess: Exit status: 0
 INFO box_register: Registered box bento/ubuntu-14.04 with id 8fac874b-5435-450e-bfbe-98802b808a89
DEBUG box_register: Writing box id '8fac874b-5435-450e-bfbe-98802b808a89' to /Users/kevin/.vagrant.d/boxes/bento-VAGRANTSLASH-ubuntu-14.04/2.3.1/parallels/box_id
 INFO subprocess: Starting process: ["/usr/local/bin/prlctl", "set", "8fac874b-5435-450e-bfbe-98802b808a89", "--template", "off"]
DEBUG subprocess: Command not in installer, not touching env vars.
 INFO subprocess: Command not in installer, restoring original environment...
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stdout:
The VM has been successfully configured.
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
DEBUG subprocess: Exit status: 0
 INFO environment: Released process lock: d1462f4d99b89da131ee008a29e1b2b7
DEBUG environment: Attempting to acquire process-lock: dotlock
 INFO environment: Acquired process lock: dotlock
 INFO environment: Released process lock: dotlock
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::PrepareClone:0x00000101302148>
 INFO warden: Calling IN action: #<VagrantPlugins::Parallels::Action::PrepareCloneSnapshot:0x00000100bec110>
 INFO warden: Calling IN action: #<VagrantPlugins::Parallels::Action::Import:0x000001013344b8>
 INFO import: Disabling password restrictions: clone-vm
 INFO subprocess: Starting process: ["/usr/local/bin/prlsrvctl", "info", "--json"]
DEBUG subprocess: Command not in installer, not touching env vars.
 INFO subprocess: Command not in installer, restoring original environment...
DEBUG subprocess: Selecting on IO
```

It essentially seems like commands that shell out to `prlsrvctl` are getting a response back very slowly. I might try restarting my computer, but thought to file this.

**Comment by wizonesolutions** [comment]
Even manually running `prlsrvctl`, e.g. `/usr/local/bin/prlsrvctl net info vagrant-vnet3 --json`, takes a pretty long time (a few minutes?). Is this a bug in the latest PD patch release? I am attempting a reinstall to see if that helps.

**Comment by wizonesolutions** [comment]
Reinstalling apparently resolved it.

**Comment by wizonesolutions** [comment]
So I had a different issue where `prlctl` and `prlsrvctl` were timing out, and I uninstalled + reinstalled. However, now I'm getting this issue _again_.

Not sure what causes it. I have the latest `vagrant-parallels`. I'll try installing over the existing copy without uninstalling first...

**Comment by wizonesolutions** [comment]
No luck. I will contact Parallels Support.

**Comment by wizonesolutions** [comment]
@legal90 Do you know anything about this by chance? I don't think Facebook support is comprised of engineers who can help me very well. Going to try restarting again and hopefully that unsticks `prlsrvctl`.

**Comment by wizonesolutions** [comment]
No dice. Don't know what to do to debug next. Hmm, maybe strace?

**Comment by wizonesolutions** [comment]
No luck :(

```
sudo dtruss prlsrvctl net info Shared --json                                                                                                     -1- 19:13:03
dtrace: system integrity protection is on, some features will not be available

dtrace: failed to execute prlsrvctl: dtrace cannot control executables signed with restricted entitlements
```

**Comment by romankulikov** [comment]
@wizonesolutions, please send us a problem report and post it here. Will try to investigate.

**Comment by wizonesolutions** [comment]
@romankulikov Already sent, but I don't know where to access them order to give you the ID. It was error code 15.

**Comment by romankulikov** [comment]
@wizonesolutions, hmmm. Well, lets try again. Reproduce the problem and then do this in terminal:
```
$ /Applications/Parallels\ Desktop.app/Contents/MacOS/prlsrvctl problem-report -s
```
The output should be like
```
Operation progress    100%

The problem report was successfully sent with id: 156347852
```
If the command fails try this:
```
$ /Applications/Parallels\ Desktop.app/Contents/MacOS/prlsrvctl problem-report -s --stand-alone
```

**Comment by wizonesolutions** [comment]
It's completely hung. I ran it before I went out today, and when I came back 7 hours later it was still going. Let me try the stand-alone mode.

**Comment by wizonesolutions** [comment]
Standalone worked, @romankulikov. Problem ID: 156444213

**Comment by romankulikov** [comment]
> Standalone worked, @romankulikov. Problem ID: 156444213

@wizonesolutions, thanks! The issue with timeout is caused by our product stalls in OS X method to enumerate host printers. Since it is suspected to be internal OS X problem the only known functional way to workaround it is to try to reboot Mac.

We saw such hangs before but now idea how to reproduce it. So it would be great if you help us to localize this accidental issue.

**Comment by wizonesolutions** [comment]
@romankulikov Sure, how could I help reproduce? I will try restarting and see if it gets better. 

1. Can I somehow disable host printer enumeration for now?
1. Maybe it is choking on my Windows VM? That one is on an external disk that is not connected right now. But it's usually not connected, and it hasn't had problems before...so maybe not.

**Comment by wizonesolutions** [comment]
No luck after a restart :( guess I will try again

```
» prlctl list                                                                                                                                          20:16:20
PrlSrv_SetNonInteractiveSession: Operation timeout. The operation could not be completed due to a timeout.
```

The first time I open PD I always get a bunch of errors after a bit though. Instead of closing them I'll submit reports and paste the ticket numbers here...maybe there will be some additional info.

**Comment by wizonesolutions** [comment]
So this is my PD startup every time lately:

<img width="1440" alt="fullscreen_21_02_2017__20_37" src="https://cloud.githubusercontent.com/assets/344116/23183941/ad18b556-f875-11e6-8fb3-0ae9f643e0b6.png">

I think I should try installing the latest again...

I'm trying to generate problem reports but I'm guessing it'll fail since it is using prlsrvctl in the background in the first place...I'll generate another one manually though...

...OK, *problem ID 156781324* @romankulikov

**Comment by wizonesolutions** [comment]
Found a workaround!!! https://www.jamf.com/jamf-nation/discussions/8695/programmatically-reset-printing-system-via-command-line#responseChild88985

I did everything except removing all printers at the end, and that seemed to unstick the Printers & Scanners dialog (even that was hanging, so I googled for how to troubleshoot that). Now Parallels seems to be unstuck for the time being. No clue how I caused the issue, though...I think I updated Parallels from the version that Homebrew Cask currently has and then restarted my computer. And then uninstalled and reinstalled fully while it was going on. Perhaps Parallels is listing the printers in a suboptimal way that causes some hangup occasionally, e.g. around upgrades when printers are not available (this happened while I was away from home and thus my default printer not available).

**Comment by romankulikov** [comment]
Frankly speaking I doubt Parallels Desktop update can influence on CUPS internals. But it would be great if you provide us those old CUPS config files which caused hangs – may be they can help us to reproduce the problem ourselves.

Anyway, great to know that the issue is gone and thanks for information provided!

**Comment by wizonesolutions** [comment]
@romankulikov this is happening again. I think it might be related to forcing the computer off and on — I had to do that. Although another VM started and stopped fine, so not sure.

Where can I send you CUPS files?

**Comment by romankulikov** [comment]
@wizonesolutions just share them in any resource you like.

**Comment by herzi** [comment]
I experience this as well. Maybe parallels should not wait for this call to finish before going on?

**Comment by damirm** [comment]
Have the same problem.
