### ISSUE TITLE
Can create folders and edit files but not create files to /vagrant

### ISSUE THREAD

**Issue by jamesla** [Parallels/vagrant-parallels#300]
Using the parallels provider I am unable to write files to /vagrant (ie touch /vagrant/test) however I can edit existing files and I can create folders.

Initially I was just using the default mapping (not specified) in my vagrantfile which gave me the error 

```
touch: cannot touch '/vagrant/test': Permission denied
```

So I added the following to my vagrant file

  ```
config.vm.synced_folder "ansible", "/vagrant", group: 'vagrant', owner: 'vagrant', mount_options: ['share', 'nosuid']
```
Output of mount | grep vagrant

`vagrant on /vagrant type prl_fs (rw,nosuid,relatime,sync)`

Which causes the same error.

The strange thing is that I can edit existing files and I can create directories no problem.

Does anybody know how to make shared folders work correctly in parallels?

**Comment by legal90** [comment]
@jamesla Could you please describe how we can reproduce that issue? Vagrantfile would be great.

In my case, everything works fine in a clean Ubuntu 16.04 installation from `bento/ubuntu-16.04` box:

```
$ vagrant init bento/ubuntu-16.04
$ vagrant up
...

$ vagrant ssh -c 'touch /vagrant/test && ls -la /vagrant/test'
-rw-rw-r-- 1 vagrant vagrant 0 Jun 14 16:50 /vagrant/test
```

**Comment by jamesla** [comment]
@legal90 After a bit of playing around, the bento image you posted works fine however this ubuntu 17 image has the issue.   

`config.vm.box = "wholebits/ubuntu17.04-64"`

To reproduce create a box using that image and touch /vagrant/test

**Comment by legal90** [comment]
I can confirm that it could be reproduced on `wholebits/ubuntu17.04-64` box version [2017.06.09](https://atlas.hashicorp.com/wholebits/boxes/ubuntu17.04-64/versions/2017.06.09)
@romankulikov Could you please take a look on it?
```
$ strace touch /vagrant/touch
<...>
open("/media/psf/vagrant/touch2", O_WRONLY|O_CREAT|O_NOCTTY|O_NONBLOCK, 0666) = -1 EACCES (Permission denied)
utimensat(AT_FDCWD, "/media/psf/vagrant/touch2", NULL, 0) = -1 ENOENT (No such file or directory)
<...>
write(2, "cannot touch '/media/psf/vagrant"..., 40cannot touch '/media/psf/vagrant/touch') = 40
```
```
mount | grep prl_fs
vagrant on /media/psf/vagrant type prl_fs (rw,nosuid,nodev,noatime,sync)
```
Parallels Tools version is 12.2.0, the same as a host part.

P.s. I'm not sure, but it might be caused by the custom patch made in this box on the build time:
https://github.com/wholebits/baseboxes/blob/f0df7573f2725b507eb8fd6011472b55a7a1e660/scripts/ubuntu17.04.sh#L25

**Comment by jamesla** [comment]
Ignore this, it turned out it was a way the box was provisioned and has been corrected on the box. Thanks guys.

**Comment by romankulikov** [comment]
> P.s. I'm not sure, but it might be caused by the custom patch made in this box on the build time:
https://github.com/wholebits/baseboxes/blob/f0df7573f2725b507eb8fd6011472b55a7a1e660/scripts/ubuntu17.04.sh#L25

Hm. Looks funny but cannot image how dropping symlink operation may cause inability to create file in prl_fs root.
