### ISSUE TITLE
Unable to install; rb-fsevent dependency conflict

### ISSUE THREAD

**Issue by mtslzr** [Parallels/vagrant-parallels#302]
Fresh macOS 10.12 install (10.12.5 to be exact). Downloaded Vagrant 1.9.7 from their website, and running "vagrant plugin install vagrant-parallels" gives the following error:

```
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

conflicting dependencies rb-fsevent (= 0.9.8) and rb-fsevent (= 0.10.2)
  Activated rb-fsevent-0.10.2
  which does not match conflicting dependency (= 0.9.8)

  Conflicting dependency chains:
    rb-fsevent (= 0.10.2), 0.10.2 activated

  versus:
    rb-fsevent (= 0.9.8)

  Gems matching rb-fsevent (= 0.9.8):
    rb-fsevent-0.9.8
```

Installing either version manually doesn't help, and I've tried blowing away my ~/.gem and ~/.vagrant.d folders to start fresh with no luck. Googling isn't turning up anything; not sure what I'm missing (not typically a Ruby person, so apologies in advance).

EDIT: Running Parallels Desktop 12 for Mac (12.2.1, 41615)

**Comment by legal90** [comment]
There could be a conflict with other plugins installed. Please, show the output `vagrant plugin list`

**Comment by mtslzr** [comment]
```
> vagrant plugin list
vagrant-share (1.1.9, system)
```

**Comment by legal90** [comment]
Hm... It looks weird. I can't reproduce it.
Pinging @chrisroberts. Chris, do you have any suggestion how to troubleshoot this kind of errors? 
I don't see any `Gemfile.lock` in Vagrant installation which could potentially have this lock: `rb-fsevent (= 0.9.8)`...

**Comment by chrisroberts** [comment]
:wave: 

@mtslzr Can you provide a gist of the output from running the install command with debug output (adding the `--debug` flag). That should help provide some context on the underlying issue.

@legal90 You are correct there is no `Gemfile.lock` used internally. The `Vagrant::Bundler` class no longer builds off bundler. When Vagrant loads, it imposes strict constraints on all internally defined rubygem libraries that are shipped within the installer. This prevents conflicting versions of rubygems being available to be activated at runtime.

**Comment by mtslzr** [comment]
Womp womp... removed ~/.gem and ~/.vagrant.d and ran the Vagrant uninstall again to make sure everything was cleared out. Reinstalled 1.9.7... and it worked. Only wanted rb-fsevent 0.10 now.

Sorry, guys. Chalk it up to a user error. :| Thanks for the help!
