### ISSUE TITLE
Running Homestead On Parallels In High Sierra 10.13.0-beta4 Fails

### ISSUE THREAD

**Issue by mikebronner** [Parallels/vagrant-parallels#305]
/cc @romankulikov 

This is a continuation of the short discussion on issue #279 .

Vagrant 1.9.2
Parallels 12.2.1 (41615)
vagrant-parallels 1.7.1

I submitted a technical report from within Parallels help menu: #199801169.

```
$ csrutil status
System Integrity Protection status: disabled.
```

**Comment by romankulikov** [comment]
Well, now things are much clear. You want to configure virtual machine with id "6313fe4a-efc0-483c-b10a-11ebb22b5927" (name "homestead-7").  It is registered by path "/Users/mike/Parallels/homestead-7.pvm" but that doesn't exist. Thus you receive respective prlctl error.

And all this has nothing to do with High Sierra.

**Comment by mikebronner** [comment]
Let me check back, I wonder if reinstalling parallels got rid of my old settings with the location of my vm folder.

**Comment by mikebronner** [comment]
Ah, yes, so I got past that issue by removing and re-adding the VM to parallels. After that I got the following errors (and submitted new technical report #200076349):
<img width="465" alt="screen shot 2017-07-27 at 12 12 17 pm" src="https://user-images.githubusercontent.com/1791050/28688021-50834cfa-72c5-11e7-98fb-e29be689d5a1.png">
<img width="472" alt="screen shot 2017-07-27 at 12 12 32 pm" src="https://user-images.githubusercontent.com/1791050/28688023-524dc114-72c5-11e7-98b2-04b134dcb511.png">
<img width="464" alt="screen shot 2017-07-27 at 12 12 42 pm" src="https://user-images.githubusercontent.com/1791050/28688026-53fd2806-72c5-11e7-808d-2750767d8a8d.png">
<img width="1015" alt="screen shot 2017-07-27 at 12 15 17 pm" src="https://user-images.githubusercontent.com/1791050/28688030-55bd503a-72c5-11e7-831f-d3e273eba5b8.png">

**Comment by romankulikov** [comment]
Ok. Now VM is found correctly but there's no disk bundle inside it. VM is configured to have "harddisk1.hdd" virtual disk bundle inside but there's no such or at least some files are missing. Seems you should recreate this VM from scratch or restore from backup.

**Comment by mikebronner** [comment]
I just can't help but wonder if something is just wrong, because prior to upgrading to High Sierra it was working, and when I look at the VM settings, the harddisk is listed in the settings. Sure, as you mentioned, you have been having some trouble with getting Parallels to work right under the new beta, so not expecting it to work. Just trying to help shed light on some of the issues.

My expectation as an end user would be that I can use a VM from before upgrading to High Sierra without having to rebuild it (and loosing all the data in it).

I'll go ahead and rebuild and report back.

Thanks! :)

**Comment by romankulikov** [comment]
All this is offtopic totally. But nevertheless.

You're right with your expectations that VM should work normally after macOS upgrade. So it would be great if you shed some light on the steps you've made during this upgrade.

What I can see is that there was valid VM of the file system. Then there was Hight Sierra installation and VM became invalid. That's it. No Parallels Desktop role here. Glitches with brand new APFS? No idea.

**Comment by mikebronner** [comment]
Absolutely, this is now more a chasing-the-white-rabbit situation. :) It's nearly impossible for me to backtrack. What I can do is restore the VM from a backup to eliminate anything outside of Parallels' influence (for example, if High Sierra upgrade to beta 4 broke it.) I don't think it is APFS itself, as I have been using it without issue in beta1 through beta3. Possibly they changed something in APFS in beta4, if that's to blame.

**Comment by mikebronner** [comment]
@romankulikov I was able to retest the issue:

1. Copied entire VM from daily driver computer (confirmed working on beta 3, use it every day) to beta 4 computer.
2. VM launched and booted, but reported issues with the network.
3. Homestead does not finish its initialization process when running `homestead up` or vagrant up, as it cannot make a connection over SSH.

I also uploaded a new technical report:200948339. So right now I am not able to get a perfectly running VM to run under beta 4 just yet. If you see anything in the technical report and have any recommendations you would like me to try, please let me know. :) Thanks!

**Comment by mikebronner** [comment]
Update: creating a homestead vagrant VM from scratch seems to work. I submitted another tech report for this, in case it helps you see what the differences are: 200967301.

**Comment by romankulikov** [comment]
I can see from the logs that VM bundles became broken two days _before_ OS upgrade to Beta4. Even more these VM-s were not running at that moment. So this definitely is an external damage factor, not a product. Even if there're glitches in Parallels Desktop or vagrant-parallels plug they are really shadowed by this VM destruction. So I'm closing this ticket. Feel free to reopen it or file a new one if there's more clear circumstances to investigate.

**Comment by mikebronner** [comment]
Sounds good. Just to clarify though: the VM was working on the beta3 computer 1 hour prior to transferring it over the beta4 computer. Not sure what was being indicated as broken in that report. Perhaps the boot process under beta 4 damages something. Just a thought. Will keep monitoring this over future betas. Thanks!

**Comment by mikebronner** [comment]
Quick update: beta 5 seems to work OK with SIP enabled (`csrutil enable`). I haven't testing creating a new VM from scratch, but it boots up my previously created VM (created under beta 4 with SIP disabled).
