### ISSUE TITLE
Deprecate official parallels boxes in favor of bento boxes?

### ISSUE THREAD

**Issue by legal90** [Parallels/vagrant-parallels#329]
The question is mostly addressed to Parallels guys, but the community suggestions are also welcomed.

As we can see, the "official" `parallels/*` boxes which I used to maintain while working at Parallels, are not updated for almost 2 years: https://app.vagrantup.com/parallels. 

Those boxes were derived from Chef's project https://github.com/chef/bento, which is the most popular community project of Packer templates for building Vagrant boxes.
This project is still going and guys there are doing amazing job. They maintain templates, rebuild boxes periodically and publish them on Vagrant Cloud: https://app.vagrantup.com/bento (including boxes for `paralells` provider).

So, I just offer to officially mark `parallels/*` boxes as deprecated and recommend using `bento/*` boxes instead. If there are no concerns, I would update these pages accordingly in 1-2 weeks:
- https://github.com/Parallels/vagrant-parallels/wiki/Available-Vagrant-Boxes
- http://parallels.github.io/vagrant-parallels/docs/boxes/index.html

**Comment by romankulikov** [comment]
@legal90, how do you think, are there any reasons for Parallels to maintain their boxes? What's the point, for example, for somebody to select parallels-box instead of bento-? The only thing I can image at the moment is "proper" version of Parallels Tools being used.

**Comment by legal90** [comment]
@romankulikov Yes, having the vendor-recommended version of Parallels Tools is most likely the only reason why Parallels might want to maintain their own boxes. 
But if the customer wants to get the latest version of Parallels Tools it's always possible to get it by enabling `update_guest_tools` provider option. (_Though sometimes it's not a good idea_ 😉  https://github.com/Parallels/vagrant-parallels/issues/325)

So, I would recommend going for `bento/` boxes as long as Chef continue building them for our provider.

**Comment by romankulikov** [comment]
@legal90, is here anything we should discuss here? Any additional info from my side?

**Comment by legal90** [comment]
@romankulikov Not really. I just wanted to ensure that there is no intention at Parallels to maintain `parallels/*` boxes (by any reason).
So, I'm closing this issue and will update doc pages soon. 👍
