### ISSUE TITLE
High CPU usage without any running processes in the virtual machine

### ISSUE THREAD

**Issue by zhengweidi** [Parallels/vagrant-parallels#338]
![image](https://user-images.githubusercontent.com/31889177/56006505-9bb51180-5d07-11e9-9b68-73d9c143ef4d.png)

I ran the top command in the virtual machine and found no process with such a high CPU usage. I have encountered this problem many times. How can I get more debugging information?

**Comment by romankulikov** [comment]
Please, send technical report and post its id here. For this when the issue occurs run
```
prlsrvctl problem-report --send
```

**Comment by zhengweidi** [comment]
The embarrassing thing is that I have never encountered this problem since I created this issue. But i will keep an eye on this.
