### ISSUE TITLE
[Question] How to share the USB device into Guest OS

### ISSUE THREAD

**Issue by xuanzhaopeng** [Parallels/vagrant-parallels#343]
Hey team,

I'm using https://github.com/bacongravy/macinbox to put OS X into vagrant boxer with Parallels Desktop & Vagrant plugin.  But may I ask is it possible to share the specific USB Device from Host OS to Guest OS?

Thanks a lot

###

Just find something on the documents, could you please correct me if the way following is correct?

```bash
config.vm.provider "parallels" do |prl|
  prl.customize [<some command>]
end
```

However from Parallels doc, I found 2 pieces of code:
```
# From Prlsrvctl
prlsrvctl usb set <usb_dev_id> <vm_uuid | vm_name>

# From Prlctl
prlctl set <vm_id | vm_name> --support-usb30 on
prlctl set <vm_id | vm_name> --device-add usb 
``` 

From code above, from prlsrvctl we could assign host USB device to guest OS, but from Prlctl is just like Guest OS enable the USB and USB 3.0.  So it seems I have to use `Prlsrvctl` and `Prlctl` in the same time, may I ask is there a way to call Prlsrvctl from this plugin?

Thanks a lot

**Comment by romankulikov** [comment]
It is not possible to call prlctl/prlsrvctl directly from plugin but looks like [Vagrant Triggers](https://www.vagrantup.com/docs/triggers/) solve the problem: there're examples how to call shell command, for example, after virtual machine start.
