### ISSUE TITLE
There's no option to change hypervisor on Vagrant or the command line 

### ISSUE THREAD

**Issue by Velociround** [Parallels/vagrant-parallels#349]
Hi there!
I wish to use the Apple hypervisor on my Vagrant VMs.
I can change this manually from the Parallels Desktop interface, but I want to set this up on Vagrant, or else I would need to manually open every VM's settings and never `vagrant destroy` them. How do I do it? There's no mention of this on the [official documentation](http://download.parallels.com/desktop/v14/docs/en_US/Parallels%20Desktop%20Pro%20Edition%20Command-Line%20Reference.pdf).
<img width="799" alt="Captura de Tela 2020-04-01 às 11 20 34" src="https://user-images.githubusercontent.com/816290/78149914-f362f600-740c-11ea-817f-aa597f253f37.jpg">

Thanks in advance!

**Comment by legal90** [comment]
Hi @Velociround,
That should be possible to do with `customize`. Try adding this to your Vagrantfile:

```ruby
config.vm.provider "parallels" do |prl|
  prl.customize ["set", :id, "--hypervisor-type", "apple"]
end
```

**Comment by Velociround** [comment]
It works! Thank you very much. I'll drop [this link to the Parallels Vagrant configuration documentation](https://parallels.github.io/vagrant-parallels/docs/configuration.html) that mentions the `prl.customize` for other people who find this issue. I think it would be nice if the `hypervisor-type` parameter could be added to the documentation, and others, if there are more missing.
