### ISSUE TITLE
Please enable `prl.gui = true` for parity with Virtualbox and VMware providers

### ISSUE THREAD

**Issue by dragon788** [Parallels/vagrant-parallels#355]
I see that in #39 that Headless mode became the default which is fine, but it would be great if I could use the syntax that shows up in the default example if I do `vagrant init somebox` and just swap `virtualbox` and `|vb|` for `parallels` and `|prl|` in the `vb.memory = 1024` and `vb.gui = false` examples. I realize that Parallels has a few more options, but if `prl.gui = true` defaulted to `window` mode that would be the same as the other providers.

It would be great if it actually accepted `true/false` or a specific mode from the supported options `--startup-view <same | window | coherence | fullscreen | modality | headless>`, but in those cases where somebody wants to change from window to fullscreen, it might be easiest to make `true` only set `window` for the first boot, and then customize it back to `same` so that if they change the mode to full screen or another option it restarts that way. Though sometimes I go to full screen and switch my monitor configuration and would prefer it only start windowed every time, in which case I would probably set it specifically to `window` or `fullscreen` or `coherence`.

**Comment by dragon788** [comment]
On a related note, while trying to do this the prl.customize way I ran into the case where changing the startup-view mode in one Vagrantfile and destroying and starting up the VM actually caused  a window to spawn for another Parallels Vagrant VM that lived in a different directories and didn't have the startup-view set it its Vagrantfile........

In attempting to reproduce the issue what I found was that doing a `vagrant destroy -f` of the box I was testing with somehow opened up the UI of the other box. Closing that out and then doing a `vagrant up` it first starts the Control Center window and then launches the VM window.

**Comment by legal90** [comment]
Hi @dragon788,

> ... and just swap virtualbox and |vb| for parallels and |prl|

Sorry, but this use case for adding/replacing the provider was never considered as something we should support. `provider` block is actually provider-specific. Some options could look the same, but in the full spec there will be always some options which look and behave differently.

Especially for the `.gui` property. As you have noticed, Parallels Desktop has a variety of startup modes, so the recommended way here is using `.customize`:
```ruby
config.vm.provider "parallels" do |prl|
  prl.customize ["set", :id, "--startup-view", "window"]  # or any of <coherence | fullscreen | modality | headless>
end
```

The recommended way is having multiple `provider` sections in your Vagrantfile - one for each provider you want to support.

Thank you for raising the proposal, but I think that adding a new boolean `.gui`, which will partially do the same as `customize` line above, will not bring any valuable benefit. Moreover, that could lead to unexpected behavior and backward compatibility issues for those, who already has `--startup-view` overridden via `.customize`.
