### ISSUE TITLE
vagrant-parallels installation fails with vagrant 2.2.8

### ISSUE THREAD

**Issue by ondrasek** [Parallels/vagrant-parallels#356]
Vagrant plugin installation fails (see attached log files). I do have the MacOS SDK and XCode / XCode build tools installed.

[vagrant-parallels-install.log](https://github.com/Parallels/vagrant-parallels/files/4616415/vagrant-parallels-install.log)
[mkmf.log](https://github.com/Parallels/vagrant-parallels/files/4616419/mkmf.log)

**Comment by ondrasek** [comment]
I noticed that the generated CC command line contains the following argument: "-isysroot /Users/vagrant/SDKs/MacOSX10.9.sdk". This obviously does not exist and should point to /Library/...

**Comment by legal90** [comment]
Hi @ondrasek 
That is the issue of embedded ruby in Vagrant 2.2.8. It was fixed in Vagrant 2.2.9:
hashicorp/vagrant-installers#163 (comment)

Please, upgrade to Vagrant 2.2.9 and try installing the plugin again.

**Comment by ondrasek** [comment]
Thank you!
