### ISSUE TITLE
Could vagrant-parallels support nic multi driver_queues like libvirt__driver_queues?

### ISSUE THREAD

**Issue by glennWang** [Parallels/vagrant-parallels#365]
You can see the` :libvirt__driver_queues` on the following link.
https://github.com/vagrant-libvirt/vagrant-libvirt

I set `:parallels__driver_queues => 4` as the following, however, it does not work !
```
Vagrant.configure("2") do |config|
  config.vm.box = "generic/fedora32"
  config.vm.network "private_network", ip: "172.18.2.5", netmask: "255.255.255.0", :mac => "040404161205", :parallels__driver_queues => 4
end
```

**Comment by legal90** [comment]
Hi @glennWang,
The feature you are referring to is specific to KVM and Linux.
I believe, it's not supported in Parallels Desktop for Mac. @dskr99, could you please confirm that?
