### ISSUE TITLE
network problems using bigsur

### ISSUE THREAD

**Issue by xpicio** [Parallels/vagrant-parallels#369]
Hello, few days ago i update macOS to Big Sur and now when i try to use `vagrant up` (on previously working project) the network initialization fail. There isn't useful info on vagrant startup log. I have only the following error:

<img width="686" alt="Schermata 2020-11-19 alle 08 57 11" src="https://user-images.githubusercontent.com/2994719/99640395-1ba96e80-2a49-11eb-982e-43c6859933ef.png">

Here my vagrant file:
```
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  net_ip = "192.168.50"

  [
    [ "MINION03-GTW", "#{net_ip}.13", "512", "generic/ubuntu1804", "/home/vagrant/scripts"],
    [ "MINION04-HMI", "#{net_ip}.14", "2048", "tas50/windows_10", "/vagrant"],
  ].each do |vmname,ip,mem,os,mount_path|
    config.vm.define "#{vmname}" do |minion_config|
      minion_config.vm.provider "parallels" do |prl|
        prl.memory = "#{mem}"
        prl.cpus = 1
        prl.name = "#{vmname}"
        prl.update_guest_tools = true
      end

      minion_config.vm.provider "virtualbox" do |vbox|
        vbox.memory = "#{mem}"
        vbox.cpus = 1
        vbox.name = "#{vmname}"
      end

      minion_config.vm.box = "#{os}"
      minion_config.vm.hostname = "#{vmname}"
      minion_config.vm.network "private_network", ip: "#{ip}"

      minion_config.vm.synced_folder "../", mount_path

      if os.eql? "generic/ubuntu1804" then
        minion_config.vm.provision "shell", inline: <<-SHELL
          id -u demo &>/dev/null || useradd -m -s /bin/bash demo
          echo demo:demo | chpasswd
          echo "demo  ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/demo
        SHELL
      end
    end
  end  
end
```

Parallels version: 16.1.1
Vagrant version: 2.2.13
Vagrant-Parallels version: 2.0.1

**Comment by legal90** [comment]
@xpicio Thank you for the report!  Could you please elaborate the following:
1) Does `vagrant up` output contain any error or uncommon message?
2) Did you find which exact VM actually reports the error which you see in Parallels Desktop GUI?
3) Please, show the output of this command: `prlsrvctl net list`

**Comment by dskr99** [comment]
@xpicio please go to the menu of Parallels Desktop -> Help -> Send technical data and send a problem report; post here its number

**Comment by guictx** [comment]
I can confirm this issue with Big Sur.

A workaround that works for me (using Laravel Homestead provisioned VM) is to halt the machine, restore default network settings on both the VM config and Parallels preferences and then start it again.

**Comment by xpicio** [comment]
1. Here the `vagrant up` log
```
Bringing machine 'MINION03-GTW' up with 'parallels' provider...
Bringing machine 'MINION04-HMI' up with 'parallels' provider...
==> MINION03-GTW: Checking if box 'generic/ubuntu1804' version '3.0.38' is up to date...
==> MINION04-HMI: Checking if box 'tas50/windows_10' version '202002.04.0' is up to date...
==> MINION03-GTW: Connecting host to Shared network...
==> MINION04-HMI: Connecting host to Shared network...
==> MINION04-HMI: Fixed port collision for 22 => 2222. Now on port 2200.
==> MINION03-GTW: Preparing network interfaces based on configuration...
    MINION03-GTW: Adapter 0: shared
    MINION03-GTW: Adapter 1: hostonly
==> MINION03-GTW: Clearing any previously set network interfaces...
==> MINION04-HMI: Preparing network interfaces based on configuration...
    MINION04-HMI: Adapter 0: shared
    MINION04-HMI: Adapter 1: hostonly
==> MINION03-GTW: Running 'pre-boot' VM customizations...
==> MINION04-HMI: Clearing any previously set network interfaces...
==> MINION04-HMI: Forwarding ports...
    MINION04-HMI: 3389 => 3389
    MINION04-HMI: 5985 => 55985
    MINION04-HMI: 5986 => 55986
==> MINION03-GTW: Booting VM...
==> MINION04-HMI: Running 'pre-boot' VM customizations...
==> MINION03-GTW: Waiting for machine to boot. This may take a few minutes...
==> MINION04-HMI: Booting VM...
    MINION03-GTW: SSH address: 10.211.55.37:22
    MINION03-GTW: SSH username: vagrant
    MINION03-GTW: SSH auth method: private key
==> MINION04-HMI: Waiting for machine to boot. This may take a few minutes...
    MINION04-HMI: WinRM address: 10.211.55.38:5985
    MINION04-HMI: WinRM username: vagrant
    MINION04-HMI: WinRM execution_time_limit: PT2H
    MINION04-HMI: WinRM transport: negotiate
==> MINION03-GTW: Machine booted and ready!
==> MINION03-GTW: Checking for Parallels Tools installed on the VM...
==> MINION03-GTW: Setting hostname...
==> MINION03-GTW: Configuring and enabling network interfaces...
==> MINION03-GTW: Mounting shared folders...
    MINION03-GTW: /home/vagrant/scripts => /Users/xpicio/Documents/Projects/tmp/tools/bootstrap-salt-minion
==> MINION03-GTW: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> MINION03-GTW: flag to force provisioning. Provisioners marked to run always will still run.
==> MINION04-HMI: Machine booted and ready!
==> MINION04-HMI: Checking for Parallels Tools installed on the VM...
==> MINION04-HMI: Setting hostname...
==> MINION04-HMI: Configuring and enabling network interfaces...
==> MINION04-HMI: Mounting shared folders...
    MINION04-HMI: /vagrant => /Users/xpicio/Documents/Projects/tmp/tools/bootstrap-salt-minion
==> MINION04-HMI: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> MINION04-HMI: flag to force provisioning. Provisioners marked to run always will still run.
```

2. I think the error is reported from the windows virtual machine.

3. Command `prlsrvctl net list`
```
Network ID        Type      Bound To
Shared            shared
NAT server:
TCP rules:
    tcp8002 source port=8002 destination IP/VM id={5b1a1b6b-8e81-4ba7-8293-270d28d29742} destination port=8002
    tcp5434 source port=5434 destination IP/VM id={5b1a1b6b-8e81-4ba7-8293-270d28d29742} destination port=5432
    rdp source port=3389 destination IP/VM id={bd02ff55-cdb7-44f1-a84b-3e066dbb4da1} destination port=3389
    winrm source port=55985 destination IP/VM id={bd02ff55-cdb7-44f1-a84b-3e066dbb4da1} destination port=5985
    winrm-ssl source port=55986 destination IP/VM id={bd02ff55-cdb7-44f1-a84b-3e066dbb4da1} destination port=5986

Host-Only         host-only
vagrant-vnet0     host-only
vagrant-vnet1     host-only
vagrant-vnet2     host-only
Wi-Fi (en0)       bridged   en0
Belkin USB-C LA~  bridged   en7
Default           bridged   FF:FF:FF:FF:FF:FF
```

I did more tries and a few of `vagrant destroy` and again `vagrant up` and now the network list is as following:
```
Network ID        Type      Bound To
Shared            shared
NAT server:
TCP rules:
    tcp8002 source port=8002 destination IP/VM id={5b1a1b6b-8e81-4ba7-8293-270d28d29742} destination port=8002
    tcp5434 source port=5434 destination IP/VM id={5b1a1b6b-8e81-4ba7-8293-270d28d29742} destination port=5432
    rdp source port=3389 destination IP/VM id={4e886fb8-4365-4daf-bbdb-cf59de7f04b8} destination port=3389
    winrm source port=55985 destination IP/VM id={4e886fb8-4365-4daf-bbdb-cf59de7f04b8} destination port=5985
    winrm-ssl source port=55986 destination IP/VM id={4e886fb8-4365-4daf-bbdb-cf59de7f04b8} destination port=5986

Host-Only         host-only
vagrant-vnet0     host-only
vagrant-vnet1     host-only
vagrant-vnet2     host-only
vagrant-vnet3     host-only
vagrant-vnet4     host-only
vagrant-vnet5     host-only
vagrant-vnet6     host-only
vagrant-vnet7     host-only
vagrant-vnet8     host-only
Wi-Fi (en0)       bridged   en0
Belkin USB-C LA~  bridged   en7
Default           bridged   FF:FF:FF:FF:FF:FF
```

It's seems the vagrant-vnet* network adapter are never removed.

4. Report id: 354944195

Hope this help :)

**Comment by rtshome** [comment]
Same problem for me. "Vagrant up" seems to ignore the ip setting in private network and keeps creating new and new vagrant-vnet host only networks.
Vagrant version 2.2.13.

**Comment by rtshome** [comment]
I solved temporarily setting the name of the private network to the same that I see in network preferences of Parallels:

config.vm.network :private_network, ip: "X.X.X.X", name: "Host-Only"

**Comment by legal90** [comment]
Hi all, 
Thank you for the provided details! I do confirm that there is currently an issue with reading and deleting host-only network interfaces on macOS 11.0 Big Sur.

That's caused by the command `prlsrvctl net info` stopped printing the line `Bound To:` to the output on macOS 11. That causes these expression to ignore host-only network interfaces:
- https://github.com/Parallels/vagrant-parallels/blob/6b61ce4a07d4bba7b81ae434a0f11c078f7f6c7a/lib/vagrant-parallels/driver/base.rb#L202-L203
- https://github.com/Parallels/vagrant-parallels/blob/6b61ce4a07d4bba7b81ae434a0f11c078f7f6c7a/lib/vagrant-parallels/driver/base.rb#L522

I'll do my best to prepare the PR with a fix as soon as possible

**Comment by dskr99** [comment]
@xpicio > Report id: 354944195

Just looked at the report;
the reason of the error is conflicting values for the HostIPAddress in parallels configuration:
/Library/Preferences/Parallels/network.desktop.xml (several places, almost in every in Host-only network):

            <HostIPAddress>192.168.50.1</HostIPAddress>
            <DhcpIPAddress>10.37.134.1</DhcpIPAddress>

I'm not sure how this could happen; may be we missed somewhere in prlsrvctl validation of the parameters, or somewhere in the valgrant parallels scripts wrong address passed, or may be configuration file was edited manually...

Also Parallels could made more descriptive error in this case

The meaning of that HostIPAddress - is the address to assign on host to the interface of that HostOnlyNetwork. It should be unique and match subnet of the virtual network. For example for 10.37.134.x HostOnly - it can be 10.37.134.2 (must not be equal to DhcpIpAddress)

Somehow HostIPAddress became the same in your setup...

**Comment by legal90** [comment]
@dskr99 
>> I'm not sure how this could happen; may be we missed somewhere in prlsrvctl validation of the parameters, or somewhere in the valgrant parallels scripts wrong address passed, or may be configuration file was edited manually...

That is actually the expected behavior of our vagrant provider here.  When the used specifies
```
minion_config.vm.network "private_network", ip: 192.168.50.13
```
it means that Vagrant will configure this static IP on the guest side. 
So, in this case when our provider creates the host-only interface, it only sets up the appropriate host adapter IP and the net mask (it is `/24` by default, unless it's set explicitly). Here are the commands which are executed:
```
["/usr/local/bin/prlsrvctl", "net", "add", "vagrant-vnet0", "--type", "host-only"]
["/usr/local/bin/prlsrvctl", "net", "set", "vagrant-vnet0", "--ip", "192.168.50.1/255.255.255.0"]
```
As you can see, we don't add any DHCP-related parameters here, so they seem to stay unchanged since the time the interface was created (the first command)

That's how it's done in the provider code:
- https://github.com/Parallels/vagrant-parallels/blob/a124ce9c76c78a077e00c2627d903efb59286d76/lib/vagrant-parallels/action/network.rb#L446-L452

- https://github.com/Parallels/vagrant-parallels/blob/6b61ce4a07d4bba7b81ae434a0f11c078f7f6c7a/lib/vagrant-parallels/driver/base.rb#L133-L154

But as I said, it works fine for the VM because vagrant automatically configures the desired static IP later on.

__________________

FYI: In order to get DHCP enabled the user should add `type: "dhcp"`, e.q.
```ruby
minion_config.vm.network "private_network", ip: 192.168.50.13, type: "dhcp"
```

In this case DHCP will be properly configured:
```
["/usr/local/bin/prlsrvctl", "net", "add", "vagrant-vnet0", "--type", "host-only"]
["/usr/local/bin/prlsrvctl", "net", "set", "vagrant-vnet0", "--ip", "192.168.50.1/255.255.255.0", "--dhcp-ip", "192.168.50.1", "--ip-scope-start", "192.168.50.2", "--ip-scope-end", "192.168.50.254"]
```
And then the VM will receive the IP form DHCP instead of a static `192.168.50.13` (which is a bit confusing and that's why this use case not mentioned in docs).

**Comment by legal90** [comment]
Meanwhile, here is the fix for the root cause of the issue on the provider's side: https://github.com/Parallels/vagrant-parallels/pull/371. 
I testes it with `Vagrantfile` posted by @xpicio in the top message and it seems working good.

I'll give it a couple more test runs and then release it early next week.

**Comment by legal90** [comment]
This fix has been released in [vagrant-parallels `v2.1.0`](https://github.com/Parallels/vagrant-parallels/releases/tag/v2.1.0)

@xpicio Could you please verify it on your setup?

**Comment by xpicio** [comment]
@legal90 it's work 🎉 🎉 👍 thank you

I did some tries and both machines received the right ip from `Vagrantfile`: 
🟢 up (on previous broken virtual machines)
🟢 destroy (the useless vagrant-vnet* has been destroyed too) and then up
🟢 halt and then up

**Comment by legal90** [comment]
Perfect, thank you too! 👍
