### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by dnx-seek** [Parallels/vagrant-parallels#372]
Hi,

I can see the latest release was April 2019. Is there a plan to roll out a new one? Plenty of updates have gone into master since then, including the recent multi machine fix which I'm hoping to be able to use.

Thanks.

**Comment by legal90** [comment]
Hi @dnx-seek,

Yes, I'm planning to release a new version today or tomorrow.

**Comment by legal90** [comment]
v2.1.0 is released now: https://github.com/Parallels/vagrant-parallels/releases/tag/v2.1.0
