### ISSUE TITLE
Headless mode

### ISSUE THREAD

**Issue by jaspertandy** [Parallels/vagrant-parallels#39]
Hi,

I see in your first issue, you have references to running these Parallels instances, but it doesn't seem as though anything came of it and the machines I start don't run headless. Is this a hidden feature or does it not exist?

Thanks for this, by the way. I can't stand having to use VirtualBox.

**Comment by rmoriz** [comment]
Is version 10 of Parallels Desktop still missing a native headless mode?

**Comment by legal90** [comment]
@rmoriz So sad, but yes. There is no truly headless mode in Parallels Desktop 10.

**Comment by rmoriz** [comment]
@legal90 How about the "Business"-edition? this is really a show-stopper for us. (we want to use it for CI/CD with test-kitchen from chef)

**Comment by legal90** [comment]
Parallels Desktop 10 Business has a feature "Run as a service" (http://kb.parallels.com/en/121317), and it is close to "headless".  It means that Parallels services are detached from the GUI, so you can quit Parallels Desktop application and virtual machines still be running.
However, if the Parallels Desktop GUI is open and you try to start the VM with `prlctl` (like Vagrant and TestKitchen does), then the VM window appears. So, it is not "headless".

But even with standart version of PD 10 you can do this (if it is OK for you):
> Virtual Machine window will not appear if you have not started Parallels Desktop GUI. 

E.q. if Parallels Desktop is not running, you can use TestKitchen and then VMs will be started in the background, without a GUI. It might be acceptable in case you are using a dedicated host for CI/CD.

P.S. There is a chance that headless option will be available in the next version, Parallels Desktop 11 (planned to be released at Q3 2015). But I can't get more details about it now.

**Comment by rmoriz** [comment]
@legal90 Thanks a lot for this information! Let's see what version 11 will bring :)

**Comment by rickard-von-essen** [comment]
:+1:

**Comment by pgrm** [comment]
What about this now with parallels 11 pro? I think vagrant machines should by default run always headless

**Comment by legal90** [comment]
Yes, there is "Headless Mode" in Parallels Desktop 11 Pro and we should enable it by default in vagrant-parallels. 
I reopen this issue and try to implement it soon.

**Comment by legal90** [comment]
Implemented in [v1.5.0](https://github.com/Parallels/vagrant-parallels/releases/tag/v1.5.0)
Option `-startup-view` is set to `headless` for Parallels Desktop >= 11
