### ISSUE TITLE
`apt-upgrade` leads to failing `vagrant reload`

### ISSUE THREAD

**Issue by DirectRoot** [Parallels/vagrant-parallels#390]
Hi there,

When I create machines via `up` directories are mounted just fine. However after an `apt upgrade` is run, any subsequent `vagrant reload` will not mount the host directories in the VM. No output from STDERR is captured, but I SSH'd into one of the machines and manually ran the suggested command...

```
mount -t prl_fs -o uid=1000,gid=1000 vagrant /vagrant
```

Which produced the output `mount: /vagrant: unknown filesystem type 'prl_fs'.` 

I'm running:
 * Vagrant 2.2.14
 * vagrant-parallels 2.2.1
 * macOS BigSur on Apple M1

I'm using a rarely downloaded box, as there aren't many out there for ARM, but it does work _until_ the `apt-upgrade` and `reload`.

```ruby
machines=[
  {
    :hostname => "prometheus",
    :ip => "10.10.0.10",
    :box => "rueian/ubuntu20-m1",
    :memory => 1024,
    :cpus => 1
  },
  {
    :hostname => "web",
    :ip => "10.10.0.11",
    :box => "rueian/ubuntu20-m1",
    :memory => 1024,
    :cpus => 1
  },
  {
    :hostname => "kubernetes",
    :ip => "10.10.0.12",
    :box => "rueian/ubuntu20-m1",
    :memory => 2048,
    :cpus => 2
  }
]

Vagrant.configure("2") do |config|
  machines.each do |machine|
    config.vm.define machine[:hostname] do |node|
      node.vm.box = machine[:box]
      node.vm.hostname = machine[:hostname]
      node.vm.network "private_network", ip: machine[:ip]
      node.vm.provider "parallels" do |prl|
        prl.update_guest_tools = true
        prl.memory = machine[:memory]
        prl.cpus = machine[:cpus]
      end
    end
  end
end
```

Are there any packages I should specifically avoid updating? (I can get you the list of what was updated, if you need it.)

**Comment by mpdude** [comment]
Can you check if the Parallels Guest Tools are still installed/available in the guest after you did the update?

Maybe the box came with them installed by default, but your updates installed a newer kernel version, and now the tools are incompatible/cannot be loaded or so? Just guessing...

**Comment by romankulikov** [comment]
Most probably kernel was updated during `apt upgrade` but Parallels Tools kernel modules were not recompiled properly. This may be due to various reasons. I suggest to start with looking into DKMS log `/var/lib/dkms/parallels-tools/kernel-$(uname -r)-$(uname -m)/log/make.log`.

**Comment by DirectRoot** [comment]
Unsure how to check if the tools are still installed/available, I'm using SSH to access a headless VM so can't test copy/paste functionality etc. Is there another way to test over SSH? (Apart from not having the required file system type to mount a shared directory).

`uname -r` from `5.4.0-65-generic` to `5.4.0-74-generic` after `apt-upgrade`. There was a log generated at the mentioned location for the former, but not the latter, so no other obvious error to pass on.

However, I've found a Debian box that means I can avoid this, so I will! Let me know if you want any more info from the failing Ubuntu.

**Comment by romankulikov** [comment]
> Is there another way to test over SSH? 

Sure, something like (untested)
```
$ vagrant ssh -c 'cat /var/lib/dkms/parallels-tools/kernel-$(uname -r)-$(uname -m)/log/make.log'
```

**Comment by DirectRoot** [comment]
Ah yes, I checked this path within the VM and the file wasn't there. There was one for `5.4.0-65-generic` (before I updated) but not one after and then `prl.update_guest_tools = true` attempted to update Parallels tools.

**Comment by claczny** [comment]
I guess that I am facing a similar issue.
How can this be fixed in the box after the kernel upgrade please?

**Comment by leunggamciu** [comment]
It works for me again after upgrading the Parallels Tools on my VM.

Upgrade instructions: [https://kb.parallels.com/en/129740](https://kb.parallels.com/en/129740)
