### ISSUE TITLE
Provisioner is not running on "vagrant up --provision"

### ISSUE THREAD

**Issue by benlumia007** [Parallels/vagrant-parallels#400]
not sure if this is the right place to mentioned this. but here's my little frustration comes to play

`vagrant up --provision` does not work as expected to be when using other providers. I believe that whenver i use `vagrant up --provision` on other providers. it allows me to provision my scripts without doing a `vagrant reload --provision`. 

while using parallels, vagrant up --provision only checks if the virtual machine is up and running and skips the provision. this means like whenever i need to do a provision, i need to use vagrant reload --provision or vagrant halt or vagrant destroy.

Is it possible to have vagrant up with a --provision trigger whenever we use vagrant up --provision.

is very frustrating.

**Comment by legal90** [comment]
@benlumia007 Thank you for reporting this! I fixed it by #402 and released in [v2.2.4](https://github.com/Parallels/vagrant-parallels/releases/tag/v2.2.4)

**Comment by benlumia007** [comment]
@legal90 
appreciated and thanks!
