### ISSUE TITLE
Cannot install Vagrant in Parallels in my Mac M1 with arm

### ISSUE THREAD

**Issue by javiermaciasa** [Parallels/vagrant-parallels#404]
Hi I can't create the vagrant VM to use homestead, it says that is because I have an M1 processor, does this have a solution? or I have to change my computer?

thanks for your help.

**Comment by legal90** [comment]
Hi @javiermaciasa 
Unfortunately, the edition of Parallels Desktop for M1 computers doesn't have a support of `prlctl` CLI utility (https://github.com/Parallels/vagrant-parallels/issues/401#issuecomment-900250874). That makes it impossible to use this Vagrant provider on M1 computer :(

**Comment by alevlasu** [comment]
@legal90 , M1 version of Parallels Desktop has a full featured CLI support. Only macOS VM on M1 is not supported in CLI.

**Comment by alevlasu** [comment]
> Hi I can't create the vagrant VM to use homestead, it says that is because I have an M1 processor, does this have a solution? or I have to change my computer?
> 
> thanks for your help.

As far as I can see homestead doesn't have images build for M1 yet (see https://github.com/laravel/homestead/issues/1552)
There is an unofficial build: https://github.com/yodoware/homestead-arm64

**Comment by legal90** [comment]
> @legal90 , M1 version of Parallels Desktop has a full featured CLI support. Only macOS VM on M1 is not supported in CLI.

@alevlasu Thank you for the clarification! I didn't have a change to try M1 yet :)
Do you mean that `prlctl` can't be used for listing and managing VMs on M1 hosts?

**Comment by alevlasu** [comment]
> > @legal90 , M1 version of Parallels Desktop has a full featured CLI support. Only macOS VM on M1 is not supported in CLI.
> 
> @alevlasu Thank you for the clarification! I haven't had a change to try M1 yet :)
> Do you mean that `prlctl` can't be used for listing and managing macOS guests on M1 hosts?

Absolutely.

**Comment by ps-mattstuart** [comment]
I haven't created the PR yet for it but I have a version I'm working succesffully with on my M1 Pro and Parallels https://github.com/Petrosight/vagrant-parallels/tree/issue-401-m1-support

**Comment by gadelkareem** [comment]
@ps-mattstuart can you merge this?

**Comment by ps-mattstuart** [comment]
I'll look to open the PR in the coming days. It was mostly focused on getting the tests done.
Note, I recently updated the branch pretty significantly to instead of taking a setting to reach out the VM and ask what arch it is to make it automated.

**Comment by ps-mattstuart** [comment]
PR opened. @gadelkareem you can install the plugin manually, clone my branch and then check the CONTRIBUTING.md file for information on how to build and install the plugin. https://github.com/Petrosight/vagrant-parallels/tree/issue-401-m1-support

**Comment by legal90** [comment]
Fixed by #416 , thank you, @ps-mattstuart !

The fix is released in [v2.2.5](https://github.com/Parallels/vagrant-parallels/releases/tag/v2.2.5)
