### ISSUE TITLE
M1 macs: registering macOS VM images

### ISSUE THREAD

**Issue by strega-nil** [Parallels/vagrant-parallels#420]
Hi all!

We're using vagrant-parallels to run our CI VMs, and it seems like there is an issue with spinning up macOS VMs on our M1s.

We set up the box using the standard method - downloading the parallels VM, and then making modifications to it, then tar'ing it up. When we try to run it, we get the following output:

```
vcpkg@CPPMAC-ARM64-01 build-box % vagrant up
Bringing machine 'default' up with 'parallels' provider...
==> default: Registering VM image from the base box 'vcpkg/macos-base'...
Parallels VM image (*.pvm) could not be found in the directory of
'vcpkg/macos-base' box. This is usually because the image has been removed manually.
Please remove the box, re-add it, and try again.
```

when I tried to fix that by also searching for `.macvm` files, (since that seems to be the new extension), I get this error:

```
vcpkg@CPPMAC-ARM64-01 build-box % vagrant up
Bringing machine 'default' up with 'parallels' provider...
==> default: Registering VM image from the base box 'vcpkg/macos-base'...
There was an error while command execution. The command and stderr is shown below.

Command: ["/usr/local/bin/prlctl", "register", "/Users/vcpkg/.vagrant.d/boxes/vcpkg-VAGRANTSLASH-macos-base/0/parallels/macOS 12.macvm", "--preserve-uuid"]

Stderr: Failed to register the VM: The configuration file you specified is invalid. Make sure that the specified file is a valid Parallels virtual machine configuration file and it is not corrupt, or select another file.
```

I'm well aware this might just be an issue on our end, so sorry if I screwed up creating the box...

**Comment by legal90** [comment]
Hi @strega-nil ,
It should be now fixed in [v2.2.6](https://github.com/Parallels/vagrant-parallels/releases/tag/v2.2.6)
