### ISSUE TITLE
'vagrant ssh' fails with macvm boxes

### ISSUE THREAD

**Issue by bineesh-n** [Parallels/vagrant-parallels#435]
The 'vagrant ssh' command fails for macvms with latest M-series chips. Their entries are not present in /Library/Preferences/Parallels/parallels_dhcp_leases file, so ipv4 address is empty (it fails to detect whether the system started). 

More Info : 
IP address correctly displayed with "prlctl list -f <uuid> --json" option.

**Comment by bineesh-n** [comment]
@legal90 yes, it is expected. Macvms are our VMs using latest apple virtualization SDK. The DHCP server for such VMs are not controlled by parallels, so we cannot put the entry in a leases file. 

IPs of macvms available in '/private/var/db/dhcpd_leases', but we will remove the custom network mechanisms sooner or later (as per discussion with management), so I don't think using leases will be a good idea (for pvms specifically).

**Comment by romankulikov** [comment]
> @alevlasu @romankulikov Can we please get some insights from Parallels / Alludo here?
> 
> Is it expected that `.macvm` VMs don't have their IP listed in `/Library/Preferences/Parallels/parallels_dhcp_leases`, or maybe there is another file for that? Is there any other way to determine the IP of such VMs except `prlctl list` call? Thank you!

@legal90, terribly sorry. I don't work for Parallels any more and cannot help with insights.

**Comment by romankulikov** [comment]
Probably speaking about .macvm VM-s using `prlctl list` to get VM IP address may be the reasonable way.

As far as I remember in some recent versions of Parallels Desktop mechanism of guest VM IP detection was reworked on that it could be got from host side, without interaction with guest. This way one may obtain IP with `prltctl`. Unfortunately I don't have product license to check this out.

**Comment by legal90** [comment]
@romankulikov Thank you for the information! 
We will use both mechanisms for now - `prlctl` and DHCP lease file, as suggested in https://github.com/Parallels/vagrant-parallels/pull/434 .
