### ISSUE TITLE
Parallel tools can't be installed in CentOS stream 9

### ISSUE THREAD

**Issue by skyzgz** [Parallels/vagrant-parallels#481]
I've encountered an issue with the installation of Parallels tools.
My PC: MAC book, Apple M2 Pro, macOS Sequoia
Parallel Desktop: 19.1.0(54729) Parallels Desktop 19 for Mac
CentOS: Centos is a virtual machine. The OS version is CentOS Stream release 9. The kernel version is 5.14.0-533

When I install parallels tools in the centos , there is an error in the procedure.

[parallels-tools-install.log](https://github.com/user-attachments/files/17989808/parallels-tools-install.log)

I think the error is following:
/usr/lib/parallels-tools/kmods/prl_tg/Toolgate/Guest/Linux/prl_tg/prltg_compat.h:66:17: error: too many arguments to function 'get_user_pages'

But I can't find the file. In ‘/usr/lib’ folder, I can't find the 'parallels-tools' folder. So I can't edit the prltg_compat.h file.

Does anyone encountered the same issue? I have searched in the issues. But it's obsoleted.

**Comment by cjlapao** [comment]
@skyzgz can you install the tools in a VM that was not created by vagrant?

**Comment by skyzgz** [comment]
> @skyzgz can you install the tools in a VM that was not created by vagrant?

I used Parallels Desktop for Hypervisor. And the centos image was downloaded from the website. I didn't try what you mentioned.

**Comment by cjlapao** [comment]
@skyzgz From the description, I believe this is a bug in Parallels Desktop itself, meaning that it will have the same issue regardless of whether you use the Vagrant Plugin. We deal here with the Vagrant Plugin and not with any bugs in the virtualization product. You will need to reach out to support of Parallels Desktop in relation to this bug.

For now I will close it as not related to this repo, feel free to reopen if you have new information
